### ISSUE TITLE
Server crashes on facebook login if the user has no email field

### ISSUE THREAD

**Issue by kvdmolen** [DemocracyOS/app#1001]
I get this error in the Terminal when loggin in with Facebook:

```
/home/admin/app/lib/auth-facebook/strategy.js:55
  user.email = profile.emails[0].value;

TypeError: Cannot read property '0' of undefined
```

Facebook App settings should be OK:

```
LOGIN PERMISSIONS
email
Provides access to the person's primary email address. This permission is approved by default.
```

**Comment by mjlescano** [comment]
@kvdmolen In you config file, did you changed the default value for `auth.facebook.permissions` ?
If not, what's the value of `profile` variable? (remove personal data before posting it)

**Comment by kvdmolen** [comment]
No,

`auth.facebook.permissions: [ "email" ]`

And the fb profile variable:
```javascript
{
	"id": "xxx",
	"username": null,
	"displayName": "Klaas",
	"name": {
		"familyName": null,
		"givenName": null,
		"middleName": null
	},
	"gender": null,
	"profileUrl": null,
	"provider": "facebook",
	"_raw": "{\"name\":\"Klaas\",\"id\":\"xxx\"}",
	"_json": {
		"name": "Klaas",
		"id": "xxx"
	}
}
```

**Comment by mjlescano** [comment]
@kvdmolen Could you test the branch `fix/facebook-login`?

I added a fix to not let users register with a facebook account that doesn't have an email. This is a quick fix to avoid the server crash, then the idea is to do this: https://github.com/DemocracyOS/app/issues/1006. Any ideas, suggestions?

**Comment by mjlescano** [comment]
@kvdmolen it was another issue also, fixed here: https://github.com/DemocracyOS/app/commit/62b91b5ab4d359c6f9077ce2e54e55d1d36ceba0
