### ISSUE TITLE
Running index.js forever?

### ISSUE THREAD

**Issue by kvdmolen** [DemocracyOS/app#1003]
I can run the app with:
```
$ sudo make run
```

But, when I close my terminal (ssh) the app stops.

So, in the Makefile I see it actually runs `node index.js`

But if I use
```
$ node index.js
```
directly, it gives an error (module not found).

I would like to run the server continuously, for example with `forever run index.js`.
Other methods to run continuously on remote server welcome!

**Comment by mjlescano** [comment]
Hi @kvdmolen!

If it's not a bug report please stick to our [mailing list](http://groups.google.com/group/democracyos-app) or to our [Gitter](https://gitter.im/DemocracyOS/app) channel.

The error it's because you have to set `NODE_PATH=.` first. So, it would be `NODE_PATH=. forever run index.js`.
