### ISSUE TITLE
Feed items are not being deleted after deleting the forum

### ISSUE THREAD

**Issue by mjlescano** [DemocracyOS/app#1031]
In [this](https://beta.democracyos.org/) case, the forum of `Test Topic` doesnt exists anymore.
![captura de pantalla 2015-08-25 a las 19 07 23](https://cloud.githubusercontent.com/assets/558901/9480943/a37c3652-4b5c-11e5-8476-642215b115ba.png)

**Comment by slifszyc** [comment]
We should also delete all topics and related comments

**Comment by slifszyc** [comment]
We are deprecating the newsfeed on hub's homepage so this should be closed
