### ISSUE TITLE
Prevent DoS attacks

### ISSUE THREAD

**Issue by cristiandouce** [DemocracyOS/app#104]
References:

* [HOLY CRAP. nearly all nodejs http servers are vulnerable to DoS and apparently](https://groups.google.com/forum/#!topic/nodejs/007S7DUm21o)
* [wikipedia:DoS](http://en.wikipedia.org/wiki/Denial-of-service_attack)

**Comment by vmariano** [comment]
Looks like fixed from 0.10.28.

Do you have more information @cristiandouce ?
