### ISSUE TITLE
Missing 'component build' step in 'Installation' wiki page

### ISSUE THREAD

**Issue by franekp** [DemocracyOS/app#1053]
On some systems it is needed to run this command during the installation, otherwise
there is blank page at the root url. It is really troublesome for users unfamiliar with nodejs.
Add it to wiki or to your makefile.

**Comment by slifszyc** [comment]
As of version `1.0.0` of DemocracyOS we are not using `component` anymore.

Docs for DemocracyOS `1.0.0` are [https://github.com/DemocracyOS/app/tree/add/docs/docs](in this branch) until we merge it to `1.0.0`
