### ISSUE TITLE
Deploy to Heroku throws 404

### ISSUE THREAD

**Issue by jnicolau** [DemocracyOS/app#1062]
The Deploy to Heroku button throws a 404 page not found error. It links to https://github.com/DemocracyOS/app/blob/development/bit.ly/1Ov2eSL
But the "blob" folder does not exist. Somebody forgot to push it to the main branch?

**Comment by jfresco** [comment]
Thanks @jnicolau for the heads-up. It's fixed now.

**Comment by slifszyc** [comment]
:sweat:
