### ISSUE TITLE
Instances on Heroku crashes when sending e-mails

### ISSUE THREAD

**Issue by jfresco** [DemocracyOS/app#1065]
If the app is hosted on Heroku with notifier embedded and SendGrid, you get the following error on the heroku log when sending a welcome e-mail (when user signs up):
```
democracyos:notifier Job 'welcome-email' failed - reason: TypeError: undefined is not a function
```

**Comment by mjlescano** [comment]
This is because the current `agenda` version of DemocracyOS/notifier doesn't support `mongo >= 3.0`. More info: https://github.com/rschmukler/agenda/pull/205

I'm currently trying to fix it.

**Comment by mjlescano** [comment]
Closed by https://github.com/DemocracyOS/app/commit/9562ba60cea8f95759a0e598b091e88901b6ea74
