### ISSUE TITLE
Every thing is settled but when IO am trying to upload it over Heroku It gives follwoing error

### ISSUE THREAD

**Issue by dkrathi457** [DemocracyOS/app#1077]
Desktop/demoos$ git push heroku master
Counting objects: 2, done.
Writing objects: 100% (2/2), 205 bytes, done.
Total 2 (delta 0), reused 0 (delta 0)
remote: Compressing source files... done.
remote: Building source:
remote: 
remote: 
remote:  !     Push rejected, no Cedar-supported app detected
remote: HINT: This occurs when Heroku cannot detect the buildpack
remote:       to use for this application automatically.
remote: See https://devcenter.heroku.com/articles/buildpacks
remote: 
remote: Verifying deploy....
remote: 
remote: !	Push rejected to demoos1.
remote: 
To https://git.heroku.com/demoos1.git
 ! [remote rejected] master -> master (pre-receive hook declined)
error: failed to push some refs to 'https://git.heroku.com/demoos1.git'

**Comment by slifszyc** [comment]
Did you clone the repo and push it to heroku as is?

**Comment by danimcgoo** [comment]
I got this error when I was trying to push the github.io project, but then I realised it's actually the DemocracyOS/app I wanted!
