### ISSUE TITLE
'Already voted' message background color should match the button's color

### ISSUE THREAD

**Issue by gvilarino** [DemocracyOS/app#191]
To maintain coherence, it should match the color of the button

Right now, here's how it looks

Positive:
![screen shot 2013-11-19 at 4 32 18 pm](https://f.cloud.github.com/assets/2538465/1575700/838ccd22-5151-11e3-8d58-5db36225731c.png)

Abstention:
![screen shot 2013-11-19 at 4 29 51 pm](https://f.cloud.github.com/assets/2538465/1575665/3497b56a-5151-11e3-9884-2cda8e407a74.png)

Negative:
![screen shot 2013-11-19 at 4 34 23 pm](https://f.cloud.github.com/assets/2538465/1575712/a03d8eb6-5151-11e3-93e8-fcfc092b7d83.png)

**Comment by slifszyc** [comment]
We won't use the same color for now
