### ISSUE TITLE
[citizen] - Keep a `collection` (array) of emails with a verified flag

### ISSUE THREAD

**Issue by cristiandouce** [DemocracyOS/app#210]
This way, we do not have to ask the `citizen` to verify twice the same email once he updates it on it's profile.

The suggestion implies the following changes on the `citizen` model:

* __remove__ `emailValidated` boolean flag
* __add__ an array of `sub-documents` with `value` and `verified` keys. This way we can allow a `citizen` to have different `emails`, but only 1 _main_ `email`, which will be the one configured on it's `profile-settings` page.

```javascript
var CitizenSchema = new Schema({
// ...
email: { type: String, required: true },
emails: [{
  value: { type: String, required: true },
  verified: { type: Boolean, default: false }
}],
// ...
});
```
Said that...

Tasks:
- [ ] Update `citizen` model with all changes specified above.
- [ ] Update/remove any reference on code to `emailValidated` and update the `profile-settings` process to check from the array of `emails` if it's verified or not.

**Comment by slifszyc** [comment]
No for the time being.

We are including signin with Facebook and others, but not multiple emails.
