### ISSUE TITLE
Standarize endpoint query and exposure

### ISSUE THREAD

**Issue by cristiandouce** [DemocracyOS/app#212]
This mechanics should only be applied at `GET` endpoints and should the as global as possible. But for `POST` actions, endpoints have all the liberty they require to prevent hacks and stuff.

At the API `endpoint` level, we should be able to `select` the fields *requiered* from the queried documents, and at the same time, filter which ones we'd like to actually expose to the client. I was thinking on 2 separate new libs: query-select and json-expose or something alike.

Tasks:
- [ ] Create `query-select` or `query-builder` module as a middleware between `endpoint` and `db-api` or as an **in-module** of `db-api` for proper `field` selection and `query` construction.
- [ ] Create `expose` or `json-expose` module as a response middleware or an **in-module** of each API `endpoint` exposure to reduce and protect sensitive data sent to the browser.
- [ ] Apply this modules and standards to all existing and future API endpoints.

Related:

* #208

**Comment by mjlescano** [comment]
Maybe we could use:
https://www.npmjs.com/package/params
https://www.npmjs.com/package/params-validate
