### ISSUE TITLE
jshint & jslint

### ISSUE THREAD

**Issue by gvilarino** [DemocracyOS/app#247]
:shipit:

**Comment by mjlescano** [comment]
How about adding .jshintrc? #666

**Comment by jfresco** [comment]
Is not clear the difference between this and #666. I think the full requirement is to provide an appropiate `.jshintrc` file, add `jshint` runtime as a `npm` dep and include it in the buildchain.

**Comment by mjlescano** [comment]
#666 is just my proposal to a add a `.jshintrc` file and nothing else. This issue is to discuss how we should write JS and which way to enforce it. The `.jshintrc` is just one point of that.

**Comment by gvilarino** [comment]
We'll be adding this in `1.0`

**Comment by jfresco** [comment]
I suggest [ESLint](https://github.com/eslint/eslint), that supports ES6 syntax.

**Comment by mjlescano** [comment]
For now, I prefer [JSCS](http://jscs.info/overview.html). It's slower (not much) but [has ES6 support](https://github.com/jscs-dev/node-jscs/issues/561#issuecomment-73288226) and also [Auto-formatting](https://medium.com/dev-channel/auto-formatting-javascript-code-style-fe0f98a923b8).

ESLint will have Auto-formatting in a while: https://github.com/eslint/eslint/issues/2212
