### ISSUE TITLE
[iPhone]  [Vote] Vote action is not displaying any suggestive message to unregistered  users

### ISSUE THREAD

**Issue by bastianhell** [DemocracyOS/app#271]
Tested in netid-democracyos
 iPhone simulator@ Xcode 

1- Go to homepage
2- Select a law
3- Try to vote 

Result: Nothing relevant indicates the user whether their vote was placed or not
Expected result: A more suggestive indicator that allows mobile users to know that they need to register or login to place a vote.

**Comment by gvilarino** [comment]
Closed by #592
