### ISSUE TITLE
Explain why partial results are not shown

### ISSUE THREAD

**Issue by gvilarino** [DemocracyOS/app#344]
Add a "Learn more" link next to vote count that displays an explanation on why partial results arent shown.

A spanish explanation can be found [here](http://partidodelared.uservoice.com/knowledgebase/articles/272480-resultados-de-votaci%C3%B3n).

**Comment by vmariano** [comment]
Translation (aprox):

>We are not currently showing partial voting results, but are shown after voting closed. 
>This has two reasons:
> * Not influence the decision of the citizen to vote with partial results and trends.
>* Respect the methodology of the legislative chambers (either partial results are).
>Once the voting is closed, you can see all results.

**Comment by gvilarino** [comment]
@vmariano translations are already in the language files; these are not the issue here.

**Comment by slifszyc** [comment]
This really depends on each DemocracyOS deployment/fork
