### ISSUE TITLE
Remove typekit

### ISSUE THREAD

**Issue by slifszyc** [DemocracyOS/app#366]
It's kinda annoying sometimes throwing 403 and forbidding loading the app's fonts

**Comment by TheCoPa** [comment]
Votes for Source Sans Pro, Open Sans or Raleway? :+1: 

http://www.google.com/fonts#ChoosePlace:select/Collection:Source+Sans+Pro|Open+Sans|Raleway

Personally I like Lato but it is getting a little overused recently

**Comment by jfresco** [comment]
Related: https://github.com/DemocracyOS/hub/issues/23

**Comment by jfresco** [comment]
Suggestion: make font names parameterizable.

**Comment by gvilarino** [comment]
@jfresco shouldn't they be definable via `css`? That should be enough for now. More customization means a fork.
