### ISSUE TITLE
Add transifex

### ISSUE THREAD

**Issue by gvilarino** [DemocracyOS/app#418]
https://www.transifex.com

**Comment by slifszyc** [comment]
We should consider [http://formatjs.io/](FormatJS) as well

**Comment by gvilarino** [comment]
Yup. I'm not liking transifex for the little I've tried it. It doesn't feel like it suits our translation approach.

**Comment by mjlescano** [comment]
Has to do with #796

**Comment by slifszyc** [comment]
Dup https://github.com/DemocracyOS/app/issues/949
