### ISSUE TITLE
Add content editor for the non-geeks

### ISSUE THREAD

**Issue by rodowi** [DemocracyOS/app#438]
**Problem**
Editing content with HTML markup is not nice for most users.

**Proposal**
Would be awesome to add a WYSIWYG editor.

**References**
You'll find tons of front-end js editors [out there](https://github.com/search?l=JavaScript&q=WYSIWYG&type=Repositories&utf8=%E2%9C%93).
We used [CKEditor](http://ckeditor.com/) for [a project](https://github.com/mxabierto/avisos) and worked like a charm.

**Comment by jfresco** [comment]
We'll use Quill, but before we have to:
- [ ] Make it componentjs compliant
- [ ] Add support for video embedding (maybe via a [module](http://quilljs.com/blog/building-a-custom-module/) or quicker approach).

**Comment by gvilarino** [comment]
@slifszyc Quill supposedly supports/outputs `HTML`. I guess tables won't be a need for 95%+ of use cases so I wouldn't mind having that 5% rely on an external helper for tables. Let's worry about that once we get there for the 95%.

The link supplied by @jfresco provides useful information. I guess we can make separate issues out of this:

1. Integrate vanilla `quill.js` as the editor in `admin` (by componentizing it; we'd get a `DemocracyOS/quilljs` fork - we can even PR it back to them)
2. Make a [`quill.js` custom module](http://quilljs.com/blog/building-a-custom-module/) for each custom need of ours; these being:
  1. Add images via `URL` (probably already exists)
  2. Add video via `URL` (probably using [embedresponsively](https://github.com/jeffehobbs/embedresponsively))

**Comment by jfresco** [comment]
I sent [a PR](https://github.com/DemocracyOS/app/pull/640) with the basic functionality just to start to give it flight hours.
Pending stuff:
- [ ] Make styles more similar to the rest of the form controls
- [ ] Add video embed support
