### ISSUE TITLE
Improve wiki

### ISSUE THREAD

**Issue by gvilarino** [DemocracyOS/app#454]
We need to tidy up a bit our wiki. I'd like to have these sorted out:

- [ ] Create a "5-minute setup" guide for having the app up in a local box or heroku in 5 minutes.
- [ ] Tidy up the [config files](https://github.com/DemocracyOS/app/wiki/Environments-and-config-files), [env variables](https://github.com/DemocracyOS/app/wiki/Environment-variables) and [custom config settings](https://github.com/DemocracyOS/app/wiki/How-to-add-configuration-settings) pages.
- [ ] Add a link to the wiki in `README.md`. Ideally close to the beginning of the file.
- [ ] Add everything needed for `notifier` integration.

Please add suggestions below

**Comment by slifszyc** [comment]
Will continue on https://github.com/DemocracyOS/app/issues/984
