### ISSUE TITLE
Unify models all the way across the client app

### ISSUE THREAD

**Issue by slifszyc** [DemocracyOS/app#479]
Now this happens:

`sidebar` has a list of `law`s coming from `laws-filter` and ultimately `laws`

`proposal` has a different, unique, complete `law` object.

Have `proposal` depend on `laws` as well, and on a single `law` being selected, make `laws` fetch the complete object and update its own internal state.

The same for other cases that are going through the same ailment.

Feel free to comment/append if you spot additional places in the code where this happens.

**Comment by gvilarino** [comment]
We'll externalize all models to a new repo.
