### ISSUE TITLE
Rename citizen to user

### ISSUE THREAD

**Issue by slifszyc** [DemocracyOS/app#480]

**Comment by aenehc** [comment]
It's only for the collection name, or we want to change "citizen" into "user" everywhere in the app (variable name etc...) ??

**Comment by gvilarino** [comment]
Everything. Under `development`, all the data tier has been renamed; we just need to complete it.

**Comment by dalareo** [comment]
Can this renaming be the cause of notifications not working??
I get: [Fri Jan 16 2015 14:48:06 GMT+0100] ERROR: action resolve failed forgot-password (54b91694b29d7a0d3f983258) {"message":"user not found"}

**Comment by jfresco** [comment]
@dalareo Check that your environment variables are set correctly. If you are using v0.9 verify that the mongoDB URL should be `MONGOHQ_URL` instead of `MONGO_URL`.

**Comment by dalareo** [comment]
It is working now for me. It was "citizens" / "users" stuff that make notifications fail.

**Comment by gvilarino** [comment]
@dalareo check your configuration. If you stick to `master` branches, stuff should work. If you go with `development` stuff might not without some adjustments.
