### ISSUE TITLE
DOM error when submitting a reply

### ISSUE THREAD

**Issue by gvilarino** [DemocracyOS/app#492]
Whem submitting a `reply` to a comment, you get a console error if you're not part of `STAFF`

Error looks like:

```
Uncaught Error: A DOM element reference is required		app.js:11938
ClassList											app.js:11927
module.exports									app.js:52973
CommentsView.newreply							app.js:975
Emitter.emit										app.js:52035
(anonymous function)								app.js:47521
(anonymous function)								app.js:17782
Request.callback									app.js:17509
(anonymous function)								app.js:975
Emitter.emit										app.js:17854
```

**Comment by mjlescano** [comment]
@gvilarino Couldn't reproduce it, maybe it's fixed now?
![screen shot 2015-02-20 at 14 49 49](https://cloud.githubusercontent.com/assets/558901/6306161/d27c3a72-b90f-11e4-898a-cb8773dd7cc9.png)

**Comment by gvilarino** [comment]
I couldn't repro easily. Try mixing admin and non-admin users

**Comment by mjlescano** [comment]
nothing :S  Tried with both users, on Safari, Chrome and Firefox.

**Comment by gvilarino** [comment]
:closed_book:
