### ISSUE TITLE
[translations] - Add Hebrew language

### ISSUE THREAD

**Issue by mairwilliams** [DemocracyOS/app#517]
Amit Goldenberg sent the translation. 
Here is the [link](https://docs.google.com/document/d/1yxdewttzketOvTGUyy_NaE__Q8tPyR1klEOTH6mVRzs/edit#heading=h.39kk8xu).

**Comment by slifszyc** [comment]
Hebrew translations must be old and we should tackle the translations and design first.

Wontfix.
