### ISSUE TITLE
Add support for RTL languages

### ISSUE THREAD

**Issue by gvilarino** [DemocracyOS/app#518]
Hebrew, Arabic and others are RTL languages and need to be supported in sush way. Also, we should check if there are other design concerns when doing this (i.e.: changing sides of icons, the sidebar, etc?)

**Comment by s01us** [comment]
Hey all, we've just started into this at Loomio. Doing just a minimum could make a huge difference. 

here's what we did https://github.com/loomio/loomio/pull/1723/files . Basically: 
- include `dir=RTL` attribute on comments / discussion contexts for users with RTL languages 
- force the text to be left aligned (but RTL-flowing) if it's going to break the design.

---

For the longer term, you want to keep in mind what sort of design changes you might need to account for. I highly recommend taking 5 mins to change your gmail/ facebook / twitter settings to Hebrew or Arabic. Brace yourself

**Comment by gvilarino** [comment]
@s01us yeah, I had the same thoughts. I've been trying some Hewbrew/Arabic versions of popular software and there's always a design difference. I guess we'll have to make do with small increments.

**Comment by slifszyc** [comment]
We can start thinking on this after we finish https://github.com/DemocracyOS/app/issues/949

**Comment by sineau** [comment]
Hello everyone,
About a year ago me and one of my friends started working on adding Persian translation and also RTL support to your lovely app. Unfortunately, he passed away while our work was in progress, and although it was mostly finished, I didn't continue the job. Today I decided to complete the job (in his memory). 
I'm preparing a branch for pull request, and I have some questions:
- should I create new issue for this or just re-open this one?
- do I need to have two pull requests (one for Persian translation and one for RTL support) or can I combine them in one branch?
- I have to make some changes to other depending packages (in particular, toggle and toggle-parent both maintained by you). Should I take any extra steps for this or is it enough to make separate pull requests to those package?
- I was just reviewing issues #949 and #1035. For the latter I noticed you didn't add formatjs to package.json, and the former is not relevant in Persian. Is there any relevant issues or notes I have to be aware of?

**Comment by franciclo** [comment]
@sineau our sincere condolences, we are thankful for the effort people put in improving DemocracyOS and having such diverse contributions from all over the world shows that the need for technologies for better democracies is real and universal.
Now, answering your questions:
- Yes, create a new issue please.
- Make one pull request combining RTL support and the translations.
- Explain in the new issue what packages need to change and we will evaluate how to proceed.
- We haven't change the translation library to one that supports proper pluralization but we understand the need for it. Lets state the need for it in the new issue, and we'll see how to approach it one more time.
