### ISSUE TITLE
Multi language support

### ISSUE THREAD

**Issue by tarasdudar** [DemocracyOS/app#537]
Please let me know if this is not the right way to report issues. Here is what I have noticed. 

The "s" is automatically added at the end to define the plural number of participants. For example:

1 Participant
2 Participants

While this is correct for English it does not work the same way in other languages. It might be better to add separate options for single and plural words for each language.

Regards,
Taras.

**Comment by gvilarino** [comment]
@tarasdudar I'm not sure what you mean by "keywords" for the `admin`. Can you please be more specific?

**Comment by tarasdudar** [comment]
@gvilarino,

I've just described it in my comment for the issue #539.  It's about "admin-laws-form.label.tag" variable in the en.json file not accepting cyrillic characters. There are more details in my comments so please refer to those.

By the way, going back to my original post. I've installed and verified democracyOS 0.8.26 release and the issue with "Participant/s" is still there. I'm assuming it was not addressed in 0.8.26 release yet.

**Comment by gvilarino** [comment]
@tarasdudar the Participant/s issue has been addressed in `0.9.0`, which was out earlier today. Please let me know if this is fixed so I may close this.
