### ISSUE TITLE
Passing variables to the instance of democracyOS app

### ISSUE THREAD

**Issue by tarasdudar** [DemocracyOS/app#538]
This is just a question and probably a very simple one.

I want to make sure the same app is running in different languages at the same time for different users. I'm hoping I could just pass a LOCALE variable to the app when the user clicks on the link according to his/her language setting. 

Could you please let me know if this is possible and how to do it.

Thanks,
Taras.

**Comment by gvilarino** [comment]
This is not possible as of this time; currently DemocracyOS is one locale for one deployment; this has to do with how the view building process is done. We look forward to providing locale as a system setting, but for the time being you'll either have to managa with a single locale per instance of DemocracyOS or hacking up a fix and sending a Pull request ;)

**Comment by tarasdudar** [comment]
Thanks @gvilarino,

Do you want me to submit a separate future enhancement request about it for tracking purposes?

I'm assuming it's OK to have three deployments running with different LOCALE settings for three separate languages accessing the same mongodb at the same time. 

Could you please confirm if this is going to work.

**Comment by gvilarino** [comment]
@tarasdudar that's going to work perfectly. I've actually tried it in the past with no problems.

**Comment by tarasdudar** [comment]
@gvilarino,

I'd like to reopen this as a future enhancement opportunity. In my use case of democracyOS I want to run separate apps for different types of laws. I think it would make it easier for users to navigate between different types of laws and find the ones relevant to them. The idea is to basically add another level of hierarchy to the list of laws on a separate web page to make it more user friendly.

Adding another "language" dimension to this hierarchy would make it a lot more difficult to maintain. Passing LOCALE variable would make it easier. 

Please let me know what you think. On one hand this is not a high priority issue and I don't want to overload the system with unnecessary tickets. On the other hand it might be good to keep it filed somewhere for future references. There might be more people asking for it in future or there might be time to address it.
