### ISSUE TITLE
Name verification does not work for all the languages

### ISSUE THREAD

**Issue by tarasdudar** [DemocracyOS/app#539]
Name verification is invoked during registration process to make sure the proper First and Last names are used. The same function is probably used for the "keyword" verification in the "admin" module.

This function does not allow proper Ukrainian and Russian words. I'm not sure if it works for other "non English alphabet" languages. This is going to be a problem for DemocracyOS deployment in those countries. 

If it's difficult to fix perhaps this function could be enabled/disabled with some environment variable.

**Comment by gvilarino** [comment]
Hey @tarasdudar, thanks for the heads-up. I'm not quite sure what you mean, though. Do you mean that when entering cyrillic characters the `signup` forms shows a validation error?

**Comment by tarasdudar** [comment]
Thanks @gvilarino,

Let me try to clarify. Please look at lib/translations/lib/en.json.

There are following variables there:

  "Your firstname"
  "Your lastname"
  "Firstname"
  "Lastname"
  "First name"
  "Last name"
"admin-laws-form.label.author"

And the following validators:

"validators.invalid.firstname"
"validators.invalid.lastname"
"validators.invalid.author"

Тhe validators are flagging errors (invalid message is displayed on the web page) if cyrillic characters are entered in those fields in the form.

The following variable

"admin-laws-form.label.tag"

does not report any special error message but the form cannot be saved if cyrillic characters are entered in this field.

**Comment by jfresco** [comment]
Hey @tarasdudar. It seems like the regexp validator for names is not taking in consideration cyrillic characters. It's not just a matter of "language" (as stands in the title of this issue), the problem is that our validations do not consider other alphabets.
In this particular case we just have to improve [this regexp](https://github.com/DemocracyOS/app/blob/development/lib/regexps/index.js#L5) by adding cyrillic characters.

**Comment by tarasdudar** [comment]
Thanks @jfresco,

I've added cyrillic characters to this file and it fixed:

"Your firstname"
"Your lastname"
"Firstname"
"Lastname"
"First name"
"Last name"
"admin-laws-form.label.author"

But it did not fix this:
"admin-laws-form.label.tag"

Here is the error I'm getting trying to use cyrillic for the label tag

{"error":{"message":"Validation failed","stack":"MongooseError: Validation failed\n at model.Document.invalidate (/home/taras/app-development/node_modules/mongoose/lib/document.js:1021:32)\n at /home/taras/app-development/node_modules/mongoose/lib/document.js:970:16\n at validate (/home/taras/app-development/node_modules/mongoose/lib/schematype.js:610:7)\n at /home/taras/app-development/node_modules/mongoose/lib/schematype.js:627:9\n at Array.forEach (native)\n at SchemaString.SchemaType.doValidate (/home/taras/app-development/node_modules/mongoose/lib/schematype.js:614:19)\n at /home/taras/app-development/node_modules/mongoose/lib/document.js:968:9\n at process._tickCallback (node.js:372:11)","name":"ValidationError","errors":{"hash":{"message":"Path `hash` is required.","name":"ValidatorError","path":"hash","type":"required","value":""}}}}

**Comment by tarasdudar** [comment]
I'm wondering if we can make the regexp more generic and smart enough to understand any language. I've got it working for cyrillic characters but this is just a temporary fix before someone else submits another ticket about names not working for his/her specific language again.

I did a quick google search on this topic and this is the first link that came up:

http://stackoverflow.com/questions/4323386/multi-language-input-validation-with-utf-8-encoding

I'm wondering if we could try some of the ideas desribed there, like \p{Alphabetic}, etc.

I guess, I'll try it out and see how it goes.

**Comment by gvilarino** [comment]
I've studied regexps for language validation for a long time now; there's no silver bullet and making one that fits a lot of sizes isn't an easy feat; natural languages are insanely varied and contemplating them all is extremely complex; you may even hit problems when doing UTF-8 characters vs UTF-16 characters, depending on the execution engine you're running on (read [this very helpful article](http://kunststube.net/encoding/) for more on this).

All in all, we choose pragmatism and moving forward; silver bullets don't exist and all code built regarding handling of natural languages is just patch upon patch upon patch.

If you feel like coming up with an ehanced regexp, be my guest and PR away :)
