### ISSUE TITLE
localization guide for DemocracyOS?

### ISSUE THREAD

**Issue by akosmaroy** [DemocracyOS/app#540]
Hi,

I wonder if there is a localization guide for DemocracyOS, that one can review & see _all_ the activities needed to localize the site to a new language?

best regards,

Akos

**Comment by tarasdudar** [comment]
Akos,

I just went through this process trying to enable Ukrainian language. Here is the only customization I had to do:

from the main app directory
cd lib/translations/lib
cp en.json ua.json
customize ua.json accordingly. You could look at examples for other languages in this directory. There are 9 languages already there.
Then I just replaced the original en.json with the new version.
mv en.json en.json_orig
mv ua.json en.json
Go back to the main directory and recompile.

That's everything I had to do to get it going. 

I'm still tweaking my file a little bit. As soon as I'm done I'll send it to the developers and hopefully they will officially include Ukrainian in their next release. 

From that point I will be able to change the language by just changing LOCALE variable to LOCALE=ua.

Hopefully this helps.

Regards,
Taras.

**Comment by cristiandouce** [comment]
@tarasdudar just change it in the config, there is no need to replace the localization file:

https://github.com/DemocracyOS/app/blob/development/config/sample.json#L39

**Comment by tarasdudar** [comment]
Thanks @cristiandouce,

I've just tried it and it did not work. I'm assuming the new language file needs to be added to the code somewhere before we could choose it with the locale variable. 

Maybe as a future improvement idea the code could look for all the files in the 

lib/translations/lib

and build accordingly.

**Comment by vmariano** [comment]
>I've just tried it and it did not work. I'm assuming the new language file needs to be added to the code somewhere before we could choose it with the locale  variable. 

@tarasdudar Check if you miss added in to `component.json` of translations.

```
 "json": [
    "lib/ca.json",
    "lib/de.json",
    "lib/en.json",
    "lib/es.json",
    "lib/fr.json",
    "lib/fi.json",
    "lib/it.json",
    "lib/nl.json",
    "lib/pt.json"
    ],
```

**Comment by vmariano** [comment]
Nice work @tarasdudar feel free, if you want to add this info to the wiki pages.

**Comment by gvilarino** [comment]
Just added this explanation to [the official wiki](https://github.com/DemocracyOS/app/wiki/Add-a-custom-language-file)

Thanks @tarasdudar
