### ISSUE TITLE
Replace error message string by key/value translations

### ISSUE THREAD

**Issue by tarasdudar** [DemocracyOS/app#541]
There is an error message: 

"There is already a citizen using <email address>" in the sign up page if the already registered user is trying to register again. This error message is not included in the list of translation variables in en.json and therefore does not change for other languages. 

There is another variable present:
"User already exists with name %s"

which might have been intended for this situation but it's not used here.
 
Regards,
Taras.

**Comment by vmariano** [comment]
We will take a look.

https://github.com/DemocracyOS/app/blob/development/lib/models/citizen.js#L79

**Comment by gvilarino** [comment]
I once tried fixing this but there was some issue with the translations engine being used in a `mongoose` plugin and was too lazy to fix that. But yea, we should do something about that.

**Comment by gvilarino** [comment]
Closed by c2e5fcb2eb58b365d5c08c809ce6937156060c45
