### ISSUE TITLE
No token for id ...

### ISSUE THREAD

**Issue by tarasdudar** [DemocracyOS/app#542]
During signup/validate step there is a link in the email that user needs to follow. It brings the user to the 

<appname>.herokuapp.com/signup/validate/<some code> web page.

The web page dispays the message:

No token for id <some code>.

I'm not sure if this is expected behavior. Looking at e.json it appears that the user should be redirected to the web page with the following messages:

"Your email has been validated and now you are logged in"
"You're being redirected in 5 seconds"
 "You can now argue and vote on bills!"

Regards,
Taras.

**Comment by gvilarino** [comment]
@tarasdudar please update your codbase and try again; we just released `0.9.0` and the whole process is now updated (under the hood, of course). Please also check out [the migration guide](https://github.com/DemocracyOS/app/wiki/Migrating-to-0.9.0)
