### ISSUE TITLE
mandrill support for 0.8.26

### ISSUE THREAD

**Issue by tarasdudar** [DemocracyOS/app#543]
I've noticed that mandrill stopped working the moment I've upgraded to 0.8.26 from 0.8.25 release. I've downgraded to 0.8.25 and verified that mandrill is working fine in that release.

I've also noticed that the following environment variables are no longer in the list of required variables:
MANDRILL_APIKEY
MANDRILL_FROM_EMAIL
MANDRILL_FROM_NAME
MANDRILL_USERNAME

and the following variables are added:

NOTIFICATIONS_URL
NOTIFICATIONS_TOKEN

Mandrill variables are also removed from config/sample.json file.

Does it mean that mandrill is no longer supported in 0.8.26 and higher?
How do I set up the notification server?

Thanks,
Taras.

**Comment by gvilarino** [comment]
Yeah, we're ditching mandrill as a requirement for DOS; instead it's a requirement for [the notifications engine](https://github.com/DemocracyOS/notifier).

Please refer to the [migration guide for 0.9.0](https://github.com/DemocracyOS/app/wiki/Migrating-to-0.9.0). A lot's changed now and we have full notifications support.

**Comment by tarasdudar** [comment]
Thanks @gvilarino,

It's all very new to me. I went through the guide and I still have some questions I'd like to clarify. 

Here is what I think I need to do to enable the notifier.

1. Create a new notifier app on heroku.
2. Download and install the notifier from https://github.com/DemocracyOS/notifier.
3. Push it to heroku.
4. Move all the MANDRILL config variables
MANDRILL_APIKEY
MANDRILL_FROM_EMAIL
MANDRILL_FROM_NAME
MANDRILL_USERNAME
from the democracyOS app to notifier app. 
Do I need to add any other variables?

I'm not sure how to set up the following two new variables for the democracyOS app:
NOTIFICATIONS_URL - is this a path to the new heroku notifier app?
NOTIFICATIONS_TOKEN - how do I generate a token? Do I use the same token in the config files for notifier app?

Could you please let me know if the above is correct and if there is anything else I need to do.
