### ISSUE TITLE
Forgot password form submission crashes when notifier is disabled

### ISSUE THREAD

**Issue by jfresco** [DemocracyOS/app#549]
Steps to reproduce the issue:
1. Ensure `notifier` is disabled.
2. If a user is logged in, log him off.
3. Go to Login and then click on "Forgot Password?" (or just go to `/forgot`).
4. Enter a valid email address and click on "Reset Password!".

In the browser console you'll see this error:
![image](https://cloud.githubusercontent.com/assets/4335188/5630580/e3369d52-959d-11e4-89ed-d3386e742c36.png)

And in the Terminal you'll see this:
![image](https://cloud.githubusercontent.com/assets/4335188/5630592/065ebcba-959e-11e4-9a6b-8fd2311bc3f5.png)

The error is being thrown in [this line](https://github.com/DemocracyOS/app/blob/development/lib/forgot-api/lib/forgotpassword.js#L66), because `data` does not exists in that scope.

**Comment by gvilarino** [comment]
I've been working on this on the `release-0.9.0` branch; I'll be shipping the fix today.
