### ISSUE TITLE
Don't show the comments filter combo when there are no comments

### ISSUE THREAD

**Issue by gvilarino** [DemocracyOS/app#553]
Don't forget to re-enable it if there are new comments (this shouldn't be an issue unless this view is sort-of reactive and we actually poll the backend for new comments or have a persistent connection)
![screen shot 2015-01-06 at 8 28 43 pm](https://cloud.githubusercontent.com/assets/2538465/5640948/d672a8e6-95e2-11e4-8942-8b3f6ad5f520.png)

**Comment by jfresco** [comment]
@mjlescano I found an error after closing the PR. The dropdown is still shown after I delete other people's arguments and only remains mine's.
![image](https://cloud.githubusercontent.com/assets/4335188/6356273/107e9620-bc3b-11e4-8bc0-ef76e381decf.png)

Also, the dropdown only appears when there is more that one argument. The amount of arguments should be the same in the delete case.
