### ISSUE TITLE
Focus/scroll to comment input when adding additional comments

### ISSUE THREAD

**Issue by gvilarino** [DemocracyOS/app#555]
Just as with #530 but for the main comment input.

Before click:

![screen shot 2015-01-07 at 8 50 41 am](https://cloud.githubusercontent.com/assets/2538465/5649392/53ac8810-964a-11e4-941f-783988f5ad5e.png)

After click:

![screen shot 2015-01-07 at 8 50 49 am](https://cloud.githubusercontent.com/assets/2538465/5649397/59566c68-964a-11e4-81f8-5b0d2cb0df57.png)

**Comment by jfresco** [comment]
Done!
