### ISSUE TITLE
need a translation option for time stamps

### ISSUE THREAD

**Issue by tarasdudar** [DemocracyOS/app#557]
Currently the translations file does not cover time intervals. All the time stamps on the page, for example

1 min ago
2 hours ago
5 days ago
etc.

are displayed in English even though the rest of the page is displayed in language set by LOCALE variable.

Is it possible to add time keywords:
sec
min
hour/s
day/s
month/s
ago

to the translation variables?

if not, where are those defined and how do I change them manually?

**Comment by gvilarino** [comment]
These are part of the `ago` dependancy and its own i18n approach; it's out of scope or us. If you want to have more options on that you should fork that repo and require your custom version.
