### ISSUE TITLE
Use a different database for users

### ISSUE THREAD

**Issue by slifszyc** [DemocracyOS/app#559]
Users should be stored in a different db using a different db connection.

Law comments and other models should be populated using that collection (check if possible).

**Comment by tarasdudar** [comment]
Thanks @slifszyc,

I was going to ask for a similar feature. Just to confirm. This would allow running several deployments of democracyOS in parallel and the same user would be able to connect to all of them without the need to register each time, am I right?

**Comment by tarasdudar** [comment]
@slifszyc,

What is the mongoUserUrl equivalent variable name for heroku?

Would it be something like MONGO_USER_URL?

**Comment by gvilarino** [comment]
Precisely, `MONGO_USER_URL`. You can always see these matches under `lib/config/env.js`.

Warning: users in a separate DB is under `development` and therefor not considered deployable as of yet; we haven't conducted enough testing.

**Comment by gvilarino** [comment]
Closed by 781d9ce7415191c0fd8a64dfddabc7b6fe262be3
