### ISSUE TITLE
need to add capcha functionality to democracyOS

### ISSUE THREAD

**Issue by tarasdudar** [DemocracyOS/app#564]
I could easily see how the corrupt governments around the world would hire all sorts of people to attack the website. Adding capcha would not fix all the security concerns but it's becoming widely used so it might be good tool to add here as well.

**Comment by gvilarino** [comment]
The same as #563, this is sort of custom for your deployment. Please check what we did under `/signup` [in this fork](https://github.com/DemocraciaEnRed/demos); it basically has what you need.
