### ISSUE TITLE
Release 1.0.0 tasks

### ISSUE THREAD

**Issue by gvilarino** [DemocracyOS/app#568]
Write here things we need to remember for 1.0.0 launch:

- [ ] Write wiki page with instructions on how to rename the `citizens` collection to `users`.
- [ ] Write wiki page with instructions on how the separate users DB choice works.

**Comment by tarasdudar** [comment]
Maybe also update the wiki page for notifier. Especially how to set up all the variables for it in heroku.

**Comment by gvilarino** [comment]
I believe that should be an issue in the https://github.com/DemocracyOS/notifier repo, not here.

**Comment by gvilarino** [comment]
@tarasdudar we'll be revising how the notifier interacts with the app in `1.0`. We'll most probably provide an out-of-the-box solution that includes `notifier` in the app runtime so no separate application is actually needed.
