### ISSUE TITLE
"signup" and "login" links are not supported by translations

### ISSUE THREAD

**Issue by tarasdudar** [DemocracyOS/app#570]
There is a message at the bottom of the screen for the users who have not sign in yet:

"You must be signed in to argue here. Login or Signup."
"You must be signed in to vote on this law. Login or Signup."

The text "You must be signed in to argue here" is handled by "comments.sign-in-required" variable in the lib/transaltions/<locale>.json files.
The text "You must be signed in to vote on this law" is handled by "You must be signed in to vote on this law" variable.
The text "or" is handled by "common.or" variable.
But the link names "Login" and "Signup" are not getting translated. They are probably hardcoded somewhere in the code in stead of using the variables. 

There are "Signup now!", "side-comments.login", and "side-comments.signup" variables that work fine in other places. Perhaps these could be reused to fix this problem as well.

I did not get a chance to check how "comments.sign-in-required-to-vote-comments" works.

**Comment by gvilarino** [comment]
This isn't hard-coded, it's just that some localization files aren't completely translated. Look for the translation key (probably `Login` or `Signup`) and fix the issue please; then PR back.

**Comment by gvilarino** [comment]
There's already an issue to address these: #476

**Comment by tarasdudar** [comment]
Thanks @gvilarino,

Just wanted to add this comment for clarification. I see you have referenced this into #476. I'm assuming @jfresco who is assigned to #476 will look into it eventually. So this clarification is mainly for him. 

I'm using my uk.json to test translations. I've translated all the keys in this file so every time I see something in English I know it is not covered in the translations file. It's coming from somewhere else.
