### ISSUE TITLE
Unable to comment

### ISSUE THREAD

**Issue by dalareo** [DemocracyOS/app#572]
It gives the following error:

/var/www/html/app/lib/models/comment.js:58
  return text.length <= 4096;
             ^
TypeError: Cannot read property 'length' of undefined
    at model.maxTextValidator (/var/www/html/app/lib/models/comment.js:58:14)
    at /var/www/html/app/node_modules/mongoose/lib/schematype.js:627:28
    at Array.forEach (native)
    at SchemaString.SchemaType.doValidate (/var/www/html/app/node_modules/mongoose/lib/schematype.js:614:19)
    at /var/www/html/app/node_modules/mongoose/lib/document.js:968:9
    at process._tickCallback (node.js:419:13)

**Comment by vmariano** [comment]
what is your current version?
`http://localhost:3000/api`

**Comment by dalareo** [comment]
{"app":"democracyos","env":"production","version":"0.9.0","apiUrl":"/api"}

Live at http://188.166.20.57:3000/

**Comment by vmariano** [comment]
Ok,  we will take a look.

**Comment by dalareo** [comment]
Is there any better version for production? We are setting up a web for public proposals at http://mareatlantica.org
Not able to setup notifications (and user registration). I've asked at Google Group. Any support contact in Spain?

**Comment by vmariano** [comment]
> Is there any better version for production? We are setting up a web for public proposals at http://mareatlantica.org

All versions are good for production. If you are in a hurry, you can check a previous version of `0.9.0`. That don't have notifier, and a little more easy to configure.

>  Not able to setup notifications (and user registration). I've asked at Google Group.

I'm not the best to explain it. Be patient, we will response, take in mind we are doing other things too, and sometimes we are in diferent timezones (sometimes we are sleeping)

We use google group to answer the questions about [1] and the issues to report bugs. If you have a question use the list, if you have an issue report here. (First check if someone has a similar problem)

[1] https://github.com/DemocracyOS/app#links

> Any support contact in Spain?

No for the moment. We use English, to build a community, so the questions can be asked for other non-project members.

**Comment by dalareo** [comment]
Thank you very much!!

**Comment by dalareo** [comment]
Any news about this bug?? We will go online on a few days! We have translated the project to Galician. I've made a pull request.

**Comment by vmariano** [comment]
Can you see this @gvilarino ?

**Comment by gvilarino** [comment]
@dalareo keep your comments under 4096 characters and try again.

**Comment by dalareo** [comment]
I have switched to master branch as you suggested me. Everything nice except the comments, even 2 characters... nothing! Check it out at http://188.166.20.57:3000/

**Comment by gvilarino** [comment]
I just made a comment, as you can see. What isn't working is the **SIDE** commenting, which throws an error on a dependency. There is an issue which I'm looking into right now. But please try to be specific about your bug reports.

**Comment by dalareo** [comment]
You are right: I meant side comments. Everything else is working. I switched to master branch. 
Thanks!!

**Comment by gvilarino** [comment]
You can temporarily disable side-comments by commenting out the DOM element or adding the class `.hide` to it.

**Comment by gvilarino** [comment]
@dalareo this is now fixed on release `0.9.0a`. Please update your codebase and redeploy.

**Comment by dalareo** [comment]
Great!!! Thank you very much!
