### ISSUE TITLE
New comment validation fails when reply input for a previous comment is open and empty

### ISSUE THREAD

**Issue by gvilarino** [DemocracyOS/app#585]
If you have the 'new comment' input enabled and also a reply on a thread based upon a previous comment of yours, the form validation fails as if the new argumen was empty, but the empty input isn't actually empty.

![screen shot 2015-01-21 at 10 30 36 am](https://cloud.githubusercontent.com/assets/2538465/5842315/ac2a832a-a158-11e4-97ac-64496abd6537.png)

**Comment by solde9** [comment]
Is this fixed on development?

**Comment by gvilarino** [comment]
@solde9 I don't think so since there're no commits associated to this issue. Why, you can't repro?

**Comment by solde9** [comment]
I can't. May this commit is related: 621935472b85706a4bd0e4e185930cfe46768eb4

**Comment by gvilarino** [comment]
Yea, I actually opened this issue before merging that to `development`. I'll close this. Thanks for the heads-up!
