### ISSUE TITLE
Independent voting for each clause

### ISSUE THREAD

**Issue by tarasdudar** [DemocracyOS/app#590]
Not sure how difficult it would be to implement and I might have already asked about before. 

I'm wondering if it's possible to enable a separate voting for each clause.

**Comment by gvilarino** [comment]
ATM it would be pretty tough. What we've done so far as a workaround is hacing a `law` for each clause. Of course, that would only make it feasible to have one or at most two `law`s per instance. Usually users won't read A LOT of text so the best approach is generating a very good, concrete and concise summary.

**Comment by tarasdudar** [comment]
OK, thanks @gvilarino,

Maybe something to consider for future development. I'm trying to figure out what would be the best use model of DOS for collaboration on law creation. In ideal scenario there would be thouthands of ideas or corrections that people would want to propose for each law. It would be nice to have a way to quickly vote on each proposal to see what's gaining people's support. There is a capability to add a comment next to each paragraph already. What might work the best for this is to have something similar to "Like" or "Agree/Disagree" buttons next to each paragraph as well with the vote count. 

This might work even better than individual voting for each clause. I'm assuming it's as difficult to implement so this is just a brainstorming on future improvement ideas.

**Comment by jfresco** [comment]
It's an interesting idea, but I think we must collect more feedback from users and deployers about this aspect.

Some thoughts.
I'm not sure if "like/dislike/comment" is the kind of feature we want for a _paragraph_. I think if somebody agrees with every paragraph of the text, she won't click on "like", but if she disagrees with a single one, she will surely "dislike" it.
The nature of comments is to let the user point what she dislikes and make a discussion about that. The author of the topic can read the paragraph comment counter as an indicator of which paragraphs of the text are more controversial.
In a "like/dislike" approach, a controversial paragraph will gather a lot of dislikes, but I'm not sure if that will be a useful indicator of something.

Maybe we must think in what kind of feedback will be useful about a paragraph. Perhaps:
* The user's opinion about a paragraph (we achieve it with Comments)
* If a comment is positive or negative
* What things about the paragraph the users want to change. 
* If a paragraph is controversial
* ...

**Comment by tarasdudar** [comment]
Thanks José,

That's an interesting thought. I agree, simple "agree/disagree" might not
give us the full picture. Maybe we
could think about it as two stage approach. The first one could be a
discussion stage where we would look at
the number of comments or something like that and the second stage could be
a decision stage where only
votes would count.


BTW, just a thought. What if we use DOS to discuss topics like this.
This would give all of us a real time feel and feedback on how it works and
how we can improve it.

**Comment by gvilarino** [comment]
@tarasdudar we'll probably set up a DemocracyOS for DemocracyOS in a few months. There's stuff we need to do before that.

ATM I think github discussions + gitter are good enough since we're not such an enormous community (yet)

**Comment by gvilarino** [comment]
The thing with biulding new interaction to the platform is no trivial task, especially with complex interaction like the one you're proposing. Keep in ming that each button/choice you present to the user adds in complexity and threatens simplicity.

Our top priority is keeping DOS as simple as possible; the tool should never get in the way.

**Comment by tarasdudar** [comment]
Thanks Guido,

I'm just trying to brainstorm ideas on this topic. And as with every
brainstorming usually 9 out of 10 ideas are not going anywhere. I'll think
about it some more. Maybe there are easier ways to accomplish this.

**Comment by slifszyc** [comment]
This could be a nice feature for the future.
