### ISSUE TITLE
[TypeError: Cannot call method 'filter' of null]

### ISSUE THREAD

**Issue by johnfelipe** [DemocracyOS/app#596]
How fix this

**Comment by gvilarino** [comment]
@johnfelipe please read (and comply with) our [contribution guidelines](https://github.com/DemocracyOS/app/blob/development/CONTRIBUTING.md) before opening an issue. Especially and empty and unclear issue like this one. Moreso, you'd probably find an answer by searching our google group.

**Comment by johnfelipe** [comment]
@gvilarino please support me for install democracyos im stock..

**Comment by gvilarino** [comment]
we will, this just is not the channel for support, either ask/search in our [google group](https://groups.google.com/forum/#!forum/democracyos-app) or [our gitter](https://gitter.im/DemocracyOS/app)
