### ISSUE TITLE
Handle error display properly in forgot form

### ISSUE THREAD

**Issue by gvilarino** [DemocracyOS/app#605]
This happens when you enter an email that doesn't exist in the backend:

![screen shot 2015-01-30 at 3 34 56 pm](https://cloud.githubusercontent.com/assets/2538465/5985889/4df1c866-a89e-11e4-8f14-db2a7fdb0038.png)

It should display the error as all other errors are displayed. I belive this has to do with an inconsistency with [the default error mechanism](https://github.com/DemocracyOS/app/blob/development/lib%2Fform-view%2Fform-view.js#L132-L147) and how errors are built on different parts of the backend.

This could be made into a larger issue. Thoughts @jfresco @slifszyc ?

**Comment by jfresco** [comment]
In this case, by switching the order of the 2nd and 3rd condition we get rid of the problem. 
![image](https://cloud.githubusercontent.com/assets/4335188/6001375/ecec5e6a-aac7-11e4-8626-967d50bd6a1e.png)

I have to test it with the other forms, but I can't imagine a case where the current 3rd condition is reached.

**Comment by gvilarino** [comment]
I've made some progress on this in #610 

Closing this and will put up some better issue for a consistent, cross-application approach.
