### ISSUE TITLE
Tag icons go glitchy when tag names are shorter than 3 characters

### ISSUE THREAD

**Issue by mairwilliams** [DemocracyOS/app#607]
![image](https://cloud.githubusercontent.com/assets/7072387/5986113/3f9d6d40-a8cd-11e4-9d74-84d4d23662d3.png)

- Images show sided sometimes in relation to the hex. 
- Tag names should always show under the icons, not next to them.

**Comment by gvilarino** [comment]
This seems to happen only when tag names are too short. I made a compromise fix on prod so it doesn't look broken.

**Comment by gvilarino** [comment]
Closed by @solde9 in 7061f6de0f024deafbda62df5943fe7c43df8a16
