### ISSUE TITLE
Make usage of `balance` optional through config option

### ISSUE THREAD

**Issue by gvilarino** [DemocracyOS/app#611]
Multiple-core usage (i.e.: usage of `balance` in root `index.js`) should be optionally set via configuration; not mandatory.

**Comment by jfresco** [comment]
And what should be the default value?

**Comment by gvilarino** [comment]
`false`

Node is supposed to be a single-process approach. Also, since I'm dockerizing `DemocracyOS` it's better since containser shouldn't be running more than a single process (processes that have a PID different than `1` don't get system signals and could become zombies if containers that host them are forcely destroyed).

I'll do this as a part of what I'm working on.
