### ISSUE TITLE
Timeago.update function is creating an infinite loop, which creates CPU overhead

### ISSUE THREAD

**Issue by mjlescano** [DemocracyOS/app#615]
![screen shot 2015-02-04 at 18 31 16](https://cloud.githubusercontent.com/assets/558901/6050449/606b71f0-ac9e-11e4-95c7-49b449d3ec32.png)

![screen shot 2015-02-04 at 18 31 41](https://cloud.githubusercontent.com/assets/558901/6050448/606b5fd0-ac9e-11e4-8a4c-de7ed855e889.png)

Is happening when I enter the http://demo.democracyos.org site.

The timeago function is called from **/lib/boot/boot.js:61**

I think the ideal would be to call Timeago.update everytime an element changes, and not infinite times looking for the elements to update. Or we could increment the interval, maybe is unnoticed if it takes 1sec to update the dates.

**Comment by gvilarino** [comment]
Wow, how the hell didn't I notice this. Agree 100%; this is top priority. Do you feel like providing a fix?

**Comment by mjlescano** [comment]
sure!

**Comment by mjlescano** [comment]
Couldn't fix it in a fast way, the problem is not with the timeago component per se. It's because everytime we call Timeago() it creates a new instance, and we are calling `timeago('.ago', { lang: this.locale, interval: 10 });` in **/lib/boot/boot.js:61** and in **DemocracyOS/side-comments/js/section.js:350** for every Section.render call (that's a LOT of times).

The lazy solution would be to delete the call on the side-comments component, and rely on the one of the main App (yeahp, veery ugly).

I think it's a better option to modify the timeago component to be a singleton, that receives dom elements (not a selector, so it doesn't have to do a query for every interval), and on every interval it will loop thru all the elements and update them. e.g.:

```
var el = section.querySelector('.ago')
timeago(el, { interval: 1000 })
```

I could do any of the options for tomorrow!

**Comment by jfresco** [comment]
The problem is that the interval set is too short, either in `boot` and `side-comments`. The `update` function is being called each 10 milliseconds independently of where and how many times the component is initialized.
I'll be submitting a PR for both apps setting the interval to 10 secs.

**Comment by gvilarino** [comment]
This isn't closed until we complete the whole `side-comments` approach and merge everything
