### ISSUE TITLE
When posting a new comment, timestamp doesn't show immediately

### ISSUE THREAD

**Issue by jfresco** [DemocracyOS/app#619]
When posting a new comment, there is a delay for this label to appear:
![image](https://cloud.githubusercontent.com/assets/4335188/6069267/b3c7c736-ad61-11e4-8b7a-312b1d82d91b.png)

That's because of #615: the `timeago` polling is longer. We should force to update when posting a new comment.

**Comment by gvilarino** [comment]
Agree with forcing a trigger; I actually remember we dropped the `timeago.interval` to 10 miliseconds when we saw that happening. We never looked at CPU usage at the time.

**Comment by gvilarino** [comment]
This will happen with `side-comments` as well.

**Comment by gvilarino** [comment]
Check #620 as well
