### ISSUE TITLE
Remote store and session API are no longer working

### ISSUE THREAD

**Issue by jfresco** [DemocracyOS/app#621]
The endpoint `lib/store/index.js` relies on a `req.session` object that depends on on `sessionCookie` middleware that is no longer used (due to the implementation of JWT and its stateless nature, we are not persisting session information on server side).
Also, `remote` store type is not being used.
Consider fix or delete the `store` API.

**Comment by gvilarino** [comment]
This has to be done all in tandem with #612; please let's *not* leave any holes here; it's pretty sensitive stuff.

**Comment by jfresco** [comment]
It's not a bug, it's a refactor task. With the implementation of JWT, the `store` API is useless. I recommend to remove it.
