### ISSUE TITLE
Paging shouldn't be used for clauses/summary comments

### ISSUE THREAD

**Issue by marcbc** [DemocracyOS/app#623]
The problem can be reproduced with a low 'comments per page setting' and a higher number of clauses or summary comments in a given law.

The summary/clauses comment loading relies on a call to `lib/db-api/comment.js:getFor()` method that internally defaults to paging with a `limit: config('comments per page')`, when performing the DB query.

As a result, only 'comments per page' clause comments/summary will ever show for a law, while users are still able to add new ones.

**Comment by jfresco** [comment]
Thanks @marcbc, good find. We'll provide a solution as soon as possible.
