### ISSUE TITLE
Law edition: "closing at" doesn't meet time validation for times with (minutes < 10) 

### ISSUE THREAD

**Issue by marcbc** [DemocracyOS/app#625]
at `lib/admin-laws-form/template.jade:53`

```
        - if (law.closingAt)
          - closingAt = new Date(law.closingAt)
          - var closingAtTime = closingAt.getHours() + ':' + closingAt.getMinutes()
          - closingAt = closingAt.getFullYear() + '/' + (closingAt.getMonth() + 1) + '/' + closingAt.getDate()
```

For laws created with closing times where minutes < 10, .getMinutes will give a single digit value, resulting in times such as 12:1 instead of 12:01. 

These values don't match the time regexp and errors are shown in the form, but it might be hard to spot if you loaded a law and started adding many clauses... since it stays hidden at the top of the form.

Rendering the leading 0 for the time values in such cases would avoid the confusion.

**Comment by gvilarino** [comment]
Very good find :+1:
