### ISSUE TITLE
[SEO] - Update app title

### ISSUE THREAD

**Issue by slifszyc** [DemocracyOS/app#636]
Accidentally searching in Google for DemocracyOS demo webpage showed me the first law's title is being added to the homepage title page

![screen shot 2015-02-10 at 4 52 25 pm](https://cloud.githubusercontent.com/assets/1213542/6135201/76dbde60-b145-11e4-948a-95b31a288059.png)

For SEO reasons, the homepage should not add anything to the page title, which is set by the configuration parameter `organization name`.

**Comment by gvilarino** [comment]
+10000

**Comment by mjlescano** [comment]
I'm not seeing it anymore on google:
![screen shot 2015-02-20 at 14 52 10](https://cloud.githubusercontent.com/assets/558901/6306207/4e52a488-b910-11e4-937a-8e49532ea672.png)

I should change the content of `<title>` anyway? (Only "DemocracyOS" without the law name).

Comment aside, we are also not setting meta[name='description'] and meta[name='author'] on the layout from the config. 
![screen shot 2015-02-20 at 14 58 15](https://cloud.githubusercontent.com/assets/558901/6306273/f08e3d8e-b910-11e4-9036-d7d88c0ac86b.png)
