### ISSUE TITLE
Ease the translation proccess

### ISSUE THREAD

**Issue by mjlescano** [DemocracyOS/app#643]
It would be nice to be able, from the terminal, to select a locale translation from one language and use Google Translate API to translate it to the other languages automatically.

**Comment by gvilarino** [comment]
As by [my comment on the PR](https://github.com/DemocracyOS/app/pull/645#issuecomment-74387084); here's what I feel this should be like:

>Is it possible you add to this script the option of actually adding translated keys into the existing language file? For example:
>
>1. I code some stuff and add 2 new dictionary entries to `en.json`. For instance:
>  1. `"someComponent.welcome.text": "Welcome"`
>  2. `"someComponent.welcome.error": "Something went wrong"`
>2. I run something like `node ./bin/dos-translate en --mising`
>3. All language files apart from `en.json` get updated with the missing translations for 1.1 and 1.2.
>
>I think this isn't too far from what's already done, but it adds the auto-updating of language files, which is the one error-prone thing we have right now.

In a nut-shell: providing a CLI to translate one string to every supported lang is good but it doesn't replace the manual insertion to resulting files, which is the biggest problem, IMHO.

**Comment by mjlescano** [comment]
Here it is :D

* `node ./bin/dos-translate --from en --translate-mising`: Will take all the keys from `--from` language and fill the missing translations on the other files (translated by Google).
* `node ./bin/dos-translate --from en --to es --to ca --translate-mising`: Also, the target languages can be setted.
* `node ./bin/dos-translate --from en --list-mising`: Or only get the list of the missing translations.

Used [node-json-file](https://github.com/ljharb/node-json-file) module so it doesn't mix up all the files in the proccess, but has the con that it removes blank lines (we're using them to separate "topics"). But the pro's are that removes duplicated keys and re-indent lines.

I think it would be nice to be able to auto-sort the json files by key, but for now we can't do it because we are not using the "namespaces" everywhere, so it would be very difficult to find things by hand. [This](https://github.com/kesla/sort-json) module does it.

**Comment by mjlescano** [comment]
@gvilarino Did you ever used Bing's translation API? Or know that if would be a good choice? Because Google has 50k words for free only one time, but Bing has [2 million chars per month for free](https://msdn.microsoft.com/en-us/library/hh454950.aspx). There's a module too: https://github.com/nanek/mstranslator, so it would be an easy change.

**Comment by gvilarino** [comment]
@mjlescano never tried it, no

**Comment by mjlescano** [comment]
Thanks :), I'll start #476

**Comment by mjlescano** [comment]
@gvilarino, @jfresco, @slifszyc, The translation lib is finished :), should I add this info to the wiki?

Final dos-translate interface:
* `node ./bin/dos-translate list-missing --base en`: Find all the missing keys.
* `node ./bin/dos-translate translate-missing --base en`: Translate missing keys.
* `node ./bin/dos-translate delete-key -k "common.key"`: Delete a given key from selected language files.
* `node ./bin/dos-translate rename-key -k "common.key" -n "common.new-name-for-key"`: Rename a given key from selected language files.
* `node ./bin/dos-translate list-extra -b en`: Prints a list of the keys of `--on` that are not present on `--base`.
* `node ./bin/dos-translate delete-extra -b en`: Delete extra keys from `--on` that are not present on `--base`.
* `node ./bin/dos-translate sort`: Sort the file keys from a language(s).
