### ISSUE TITLE
Create a Newsletter functionality, that let users receive a summary of all the activity

### ISSUE THREAD

**Issue by mjlescano** [DemocracyOS/app#667]
Much like [Github's Newsletter](https://github.com/explore/subscribe).

![captura de pantalla 2015-02-24 a las 15 02 54](https://cloud.githubusercontent.com/assets/558901/6355689/83e49e5c-bc36-11e4-9d2c-e7020f513f9f.png)

![captura de pantalla 2015-02-24 a las 15 07 58](https://cloud.githubusercontent.com/assets/558901/6355748/183adaf8-bc37-11e4-8763-db6ced90c8ce.png)

**Comment by slifszyc** [comment]
Not for now...
