### ISSUE TITLE
Some of the messages are not supported by translation keys

### ISSUE THREAD

**Issue by tarasdudar** [DemocracyOS/app#671]
I've updated to the latest 0.10.13 release and there are still some places that are not supported by the translation keys. Here they are:

/signin page:
"LOGIN" button
"Don't have an account?"

/signup page:
"Repeat Password"

main page:
"Login" and "Signup" links at the bottom of the page

**Comment by gvilarino** [comment]
I guess @mjlescano should be looking into this
