### ISSUE TITLE
Improve message on Twitter/Facebook share's

### ISSUE THREAD

**Issue by santisiri** [DemocracyOS/app#672]
Use a more engaging message for Facebook and Twitter shares, including the handle of @DemocracyOS:

"I just voted in @DemocracyOS about [TOPIC TITLE] - <link>, it's your turn now."

**Comment by gvilarino** [comment]
Shouldn't we include a link to the `topic`?

**Comment by gvilarino** [comment]
Also, I think the FB share should be more thoroghly addressed (e.g.: which `og` tags should we use?)

**Comment by santisiri** [comment]
oh yeah.. I've written ' < link >' in the issue but now i realize how github parses that.

**Comment by gvilarino** [comment]
cool

**Comment by slifszyc** [comment]
duplicated https://github.com/DemocracyOS/app/issues/672
