### ISSUE TITLE
Revamp admin module

### ISSUE THREAD

**Issue by jfresco** [DemocracyOS/app#675]
Thoughts:
- [x] 1. Remove clauses for new laws but mantain backwards compatibility for laws that are using it.
- [x] 2. As we are removing clauses, improve the text truncation strategy on `proposal-article` view.
- [x] 3. Add sort & search to laws list (client side, no big deal).
- [x] 4. Add delete button on laws list.
- [x] 5. Remove admin sidebar (as we know it).
- [x] 6. Replace checkboxes with `toggle`.
- [x] 7. Revamp link list like ![image](https://cloud.githubusercontent.com/assets/4335188/6398316/89ce0dbe-bdc9-11e4-8fc1-eab7204b6068.png)
- [x] 8. Put action buttons at clearfix top right like 

![image](https://cloud.githubusercontent.com/assets/4335188/6421236/a90356f2-beab-11e4-9093-45113ed33431.png)
- [x] 9. Revamp tags list
- [x] 10. Make sidebar responsive
- [x] 11. Fix search bar items arrangement
- [ ] 12. Make action buttons fixed in non-mobile

**Comment by gvilarino** [comment]
:+1: 

I think `4.` should have a confirmation dialog as the one you see when attempting to delete an existing `law` inside the composer, or like what you see when removing a comment/reply.

 How will you address `tag` management if you do `5.`? Maybe I would remove the "Create" options and add a notiveable button on top of the "List" view, so you can tap there and just spin up the composer.

**Comment by jfresco** [comment]
>How will you address tag management if you do 5.? Maybe I would remove the "Create" options and add a notiveable button on top of the "List" view, so you can tap there and just spin up the composer.

I didn't think it enough yet. I agree with having an "Add" button on top of the lists, but I don't know yet how to switch between lists (maybe tabs?).

**Comment by gvilarino** [comment]
No tabs please

**Comment by jfresco** [comment]
I was thinking in remove permanently the list/create page of `tags` and list and create a `tag` directly from the `law` new/edit form.

**Comment by tarasdudar** [comment]
@jfresco,

I thought clauses could be a usefull tool to enable collaboration in creating new laws. The DOS use model I had in mind would allow people to propose different clauses for discussion and voting. Ideally there would be a possibility to vote on each clause individually which is not supported by DOS at the moment. Then based on the voting results some of the clauses would make it into the law and some would be rejected.

Why do you want to remove clauses?

**Comment by jfresco** [comment]
@tarasdudar Because we are implementing a rich text widget. Our intention is to encourage admin users to write the topic text in a unique place. You can still add clauses separating it by titles; also, you'll be able to nest clauses. Side comments will still work with this approach, so eventually will not be impossible to implement some feature at clause level.
