### ISSUE TITLE
Fix notifier

### ISSUE THREAD

**Issue by piamancini** [DemocracyOS/app#679]
We've been receiving complaints of some users that are getting what we believe are notifications from the tester. The "no guns no cops" new bill notification has been received my several users. @mairwilliams did not publish that bill in demo. I have also received this same notification. 

![screen shot 2015-02-26 at 4 28 22 pm](https://cloud.githubusercontent.com/assets/3671070/6403421/9a28a7fe-bdd4-11e4-93a7-669847f6bf8b.png)

**Comment by gvilarino** [comment]
done
