### ISSUE TITLE
Installed on Heroku. Mailer not working!

### ISSUE THREAD

**Issue by gdiazc** [DemocracyOS/app#682]
Hello! I successfully installed DemocracyOS on Heroku and connected it to a MongoDB instance.

I can see the start page and the sign-up form, but upon creating a new user the confirmation email is never sent. How should I configure the mailer?

Thanks!

**Comment by gvilarino** [comment]
This isn't the right place for inquiries on troubleshooting the build & run process. Please read our [contribution guidelines](https://github.com/DemocracyOS/app/blob/development/CONTRIBUTING.md) before opening an issue. You can ask this question either in our [mailing list](http://groups.google.com/group/democracyos-app) or our [official gitter](https://gitter.im/DemocracyOS/app).
