### ISSUE TITLE
fix profile picture url 

### ISSUE THREAD

**Issue by piamancini** [DemocracyOS/app#683]
URL and header overlap of image. 
![screen shot 2015-02-28 at 12 54 10 pm](https://cloud.githubusercontent.com/assets/3671070/6428092/0f50b83a-bf49-11e4-9093-342d2f402ff2.png)

**Comment by gvilarino** [comment]
@piamancini what browser are you running?

**Comment by piamancini** [comment]
chrome Version 40.0.2214.115 (64-bit)

**Comment by slifszyc** [comment]
This is fixed
