### ISSUE TITLE
Allow login not beign case-sensitive on the email

### ISSUE THREAD

**Issue by mjlescano** [DemocracyOS/app#689]
![captura de pantalla 2015-03-05 a las 17 41 52](https://cloud.githubusercontent.com/assets/558901/6514152/01ae5a7e-c35f-11e4-8730-1e200917fea2.png)

**Comment by gvilarino** [comment]
you mean our mail handling should be case-sensitive? I'm not sure. Some email-services don't support that and it may allow account duplication. I don't think this is a priority.

**Comment by mjlescano** [comment]
Nope, the contrary. I should be able to login with `fake@mail.com` and with `FAKE@mail.com`, no matter the letter casing. (Fixed the bug title :P)

**Comment by gvilarino** [comment]
I think this requires further research. Would love to hear what the community has to say about this.

**Comment by palmerabollo** [comment]
This is worth reading http://stackoverflow.com/questions/9807909/are-email-addresses-case-sensitive

+1 to @mjlescano proposal to ignore case.

**Comment by jfresco** [comment]
+1 to make email case-insensitive.

**Comment by jfresco** [comment]
What should we do with existing caps and aliased email addresses? For example, in the database the following email addresses can coexist:
* `pepe@gmail.com`
* `pepe+1@gmail.com`
* `PEPE@gmail.com`
By merging #752, the two last will become inaccessible and will be aliased to the first one.

**Comment by gvilarino** [comment]
So what's the status on this one?

**Comment by mjlescano** [comment]
Will be fixed on this pull request: #752
