### ISSUE TITLE
Button text don't show in menu

### ISSUE THREAD

**Issue by mairwilliams** [DemocracyOS/app#696]
User menu seems empty. I only see text/buttons when I mouse-over. It happens in [Nadeem Mazen](http://nadeemmazen.democracyos.org/) instance alone.

![image](https://cloud.githubusercontent.com/assets/7072387/6558639/11bbc2da-c65c-11e4-8832-00b3ba63c22b.png)

**Comment by gvilarino** [comment]
Please don't report particular implementations' bugs here.

**Comment by gvilarino** [comment]
That seems a css issue
