### ISSUE TITLE
Error: failed to read "component~emitter@1.0.0"'s file "index.js"

### ISSUE THREAD

**Issue by fulldanad** [DemocracyOS/app#700]
Hi,
 I'm trying to get it working on a synology and everything goes fine until I get the following logs when I reach the web interface on port 3000:

/volume1/manual_install/democracyos_app/lib/build/index.js:53
        if (err) throw err;
                       ^
Error: failed to read "component~emitter@1.0.0"'s file "index.js"
    at /volume1/manual_install/democracyos_app/node_modules/component-builder/node_modules/component-manifest/build/index.js:440:21
    at fs.js:207:20
    at OpenReq.Req.done (/volume1/manual_install/democracyos_app/node_modules/component-resolver/node_modules/graceful-fs/graceful-fs.js:143:5)
    at OpenReq.done (/volume1/manual_install/democracyos_app/node_modules/component-resolver/node_modules/graceful-fs/graceful-fs.js:63:22)
    at OpenReq.Req.done (/volume1/manual_install/democracyos_app/node_modules/component-builder/node_modules/graceful-fs/graceful-fs.js:143:5)
    at OpenReq.done (/volume1/manual_install/democracyos_app/node_modules/component-builder/node_modules/graceful-fs/graceful-fs.js:63:22)
    at Object.oncomplete (fs.js:107:15)
2015-03-11T00:44:08.241+0100 [conn13] end connection 127.0.0.1:53964 (9 connections now open)
2015-03-11T00:44:08.241+0100 [conn12] end connection 127.0.0.1:53963 (9 connections now open)
2015-03-11T00:44:08.241+0100 [conn15] end connection 127.0.0.1:53966 (9 connections now open)
2015-03-11T00:44:08.241+0100 [conn14] end connection 127.0.0.1:53965 (9 connections now open)
2015-03-11T00:44:08.241+0100 [conn16] end connection 127.0.0.1:53967 (7 connections now open)
2015-03-11T00:44:08.241+0100 [conn17] end connection 127.0.0.1:53968 (5 connections now open)
2015-03-11T00:44:08.241+0100 [conn18] end connection 127.0.0.1:53969 (4 connections now open)
2015-03-11T00:44:08.241+0100 [conn19] end connection 127.0.0.1:53970 (3 connections now open)
2015-03-11T00:44:08.242+0100 [conn20] end connection 127.0.0.1:53971 (1 connection now open)
2015-03-11T00:44:08.242+0100 [conn21] end connection 127.0.0.1:53972 (0 connections now open)
make: *** [run] Error 8

Could please advice how to address this ?

Regards
Motivated citizen

**Comment by gvilarino** [comment]
Did you properly set up your github token?

**Comment by fulldanad** [comment]
Yes


2015-03-11 3:33 GMT+01:00 Guido Vilariño <notifications@github.com>:

> Did you properly set up your github token?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/DemocracyOS/app/issues/700#issuecomment-78189430>.
>



-- 
Dany Amoyi
+33 603 223 219

**Comment by gvilarino** [comment]
This seem like a particular error for your environment and not a bug per-se. Please describe where and how you're building and running

**Comment by fulldanad** [comment]
It runs on a synology DS415+


bash-3.2# mongod &
[1] 20046
bash-3.2# mongod --help for help and startup options
2015-03-12T19:14:24.583+0100 [initandlisten] MongoDB starting : pid=20046
port=27017 dbpath=/data/db 64-bit host=DD
2015-03-12T19:14:24.583+0100 [initandlisten] db version v2.6.7
2015-03-12T19:14:24.583+0100 [initandlisten] git version:
a7d57ad27c382de82e9cb93bf983a80fd9ac9899
2015-03-12T19:14:24.583+0100 [initandlisten] build info: Linux
build7.nj1.10gen.cc 2.6.32-431.3.1.el6.x86_64 #1 SMP Fri Jan 3 21:39:27 UTC
2014 x86_64 BOOST_LIB_VERSION=1_49
2015-03-12T19:14:24.583+0100 [initandlisten] allocator: tcmalloc
2015-03-12T19:14:24.584+0100 [initandlisten] options: {}
2015-03-12T19:14:24.613+0100 [initandlisten]
2015-03-12T19:14:24.613+0100 [initandlisten] ** WARNING: Readahead for
/data/db is set to 2048KB
2015-03-12T19:14:24.613+0100 [initandlisten] **          We suggest setting
it to 256KB (512 sectors) or less
2015-03-12T19:14:24.613+0100 [initandlisten] **
http://dochub.mongodb.org/core/readahead
2015-03-12T19:14:24.819+0100 [initandlisten] journal dir=/data/db/journal
2015-03-12T19:14:24.834+0100 [initandlisten] recover : no journal files
present, no recovery needed
2015-03-12T19:14:25.239+0100 [initandlisten] waiting for connections on
port 27017

bash-3.2#
bash-3.2#
bash-3.2#
bash-3.2# make
Installing dependencies...
npm WARN package.json passport-local@0.1.6 No README data
npm WARN package.json co-prompt@1.0.0 No repository field.
npm WARN package.json t-component@1.0.0 repo should probably be repository.
npm WARN package.json type-component@0.0.1 No repository field.
npm WARN cannot run in wd DemocracyOS@0.10.11 node ./bin/dos-install
--config && node ./bin/dos-config && node ./bin/dos-build
(wd=/volume1/manual_install/democracyos_app)
Done.\n
Starting application...
  democracyos:config Load local configuration from
/volume1/manual_install/democracyos_app/config/development.json +0ms
  democracyos:config Merge environment set configuration variables +8ms
  democracyos:config Loaded config object for env development with sha
"c8f5e109d6d78ffdd847dce25314c06a" +6ms
js-bson: Failed to load c++ bson extension, using pure JS version
  democracyos:config Invalid config key "mongoUsersUrl" +2s
  democracyos:root Application started on port 3000 +0ms
2015-03-12T19:14:36.533+0100 [initandlisten] connection accepted from
127.0.0.1:35459 #1 (1 connection now open)
2015-03-12T19:14:36.534+0100 [initandlisten] connection accepted from
127.0.0.1:35460 #2 (2 connections now open)
2015-03-12T19:14:36.537+0100 [initandlisten] connection accepted from
127.0.0.1:35461 #3 (3 connections now open)
2015-03-12T19:14:36.537+0100 [initandlisten] connection accepted from
127.0.0.1:35462 #4 (4 connections now open)
2015-03-12T19:14:36.538+0100 [initandlisten] connection accepted from
127.0.0.1:35463 #5 (5 connections now open)
2015-03-12T19:14:36.538+0100 [initandlisten] connection accepted from
127.0.0.1:35464 #6 (6 connections now open)
2015-03-12T19:14:36.539+0100 [initandlisten] connection accepted from
127.0.0.1:35465 #7 (7 connections now open)
2015-03-12T19:14:36.539+0100 [initandlisten] connection accepted from
127.0.0.1:35466 #8 (8 connections now open)
2015-03-12T19:14:36.540+0100 [initandlisten] connection accepted from
127.0.0.1:35467 #9 (9 connections now open)
2015-03-12T19:14:36.540+0100 [initandlisten] connection accepted from
127.0.0.1:35468 #10 (10 connections now open)


Then I launch my webbrowser to access the http://192.168.1.15:3000/


And I get a blanck page with DemocracyOS as a title and the following logs.

2015-03-12T19:15:25.255+0100 [clientcursormon] mem (MB) res:51 virt:524
2015-03-12T19:15:25.255+0100 [clientcursormon]  mapped (incl journal
view):320
2015-03-12T19:15:25.255+0100 [clientcursormon]  connections:10
  democracyos:jwt HTTP header x-access-token has no token. Moving on... +0ms
  democracyos:build Build /app.css. +0ms
  democracyos:build Build /app.js. +11ms
  outdated name of a dependency : please update: "guille/ms.js" ->
"rauchg/ms.js"
  outdated name of a dependency : please update: "guille/ms.js" ->
"rauchg/ms.js"
  outdated name of a dependency : please update: "component/get-document"
-> "webmodules/get-document"
  outdated name of a dependency : please update: "component/get-document"
-> "webmodules/get-document"
  democracyos:jwt HTTP header x-access-token has no token. Moving on... +32s

/volume1/manual_install/democracyos_app/lib/build/index.js:53
        if (err) throw err;
                       ^
Error: failed to read "component~emitter@1.0.0"'s file "index.js"
    at
/volume1/manual_install/democracyos_app/node_modules/component-builder/node_modules/component-manifest/build/index.js:440:21
    at fs.js:207:20
    at OpenReq.Req.done
(/volume1/manual_install/democracyos_app/node_modules/component-resolver/node_modules/graceful-fs/graceful-fs.js:143:5)
    at OpenReq.done
(/volume1/manual_install/democracyos_app/node_modules/component-resolver/node_modules/graceful-fs/graceful-fs.js:63:22)
    at OpenReq.Req.done
(/volume1/manual_install/democracyos_app/node_modules/component-builder/node_modules/graceful-fs/graceful-fs.js:143:5)
    at OpenReq.done
(/volume1/manual_install/democracyos_app/node_modules/component-builder/node_modules/graceful-fs/graceful-fs.js:63:22)
    at Object.oncomplete (fs.js:107:15)
2015-03-12T19:16:23.961+0100 [conn1] end connection 127.0.0.1:35459 (9
connections now open)
2015-03-12T19:16:23.961+0100 [conn7] end connection 127.0.0.1:35465 (9
connections now open)
2015-03-12T19:16:23.961+0100 [conn6] end connection 127.0.0.1:35464 (9
connections now open)
2015-03-12T19:16:23.961+0100 [conn3] end connection 127.0.0.1:35461 (9
connections now open)
2015-03-12T19:16:23.961+0100 [conn2] end connection 127.0.0.1:35460 (8
connections now open)
2015-03-12T19:16:23.961+0100 [conn5] end connection 127.0.0.1:35463 (6
connections now open)
2015-03-12T19:16:23.961+0100 [conn4] end connection 127.0.0.1:35462 (9
connections now open)
2015-03-12T19:16:23.962+0100 [conn8] end connection 127.0.0.1:35466 (2
connections now open)
2015-03-12T19:16:23.962+0100 [conn9] end connection 127.0.0.1:35467 (2
connections now open)
2015-03-12T19:16:23.962+0100 [conn10] end connection 127.0.0.1:35468 (2
connections now open)
make: *** [run] Error 8
bash-3.2#



2015-03-11 23:30 GMT+01:00 Guido Vilariño <notifications@github.com>:

> This seem like a particular error for your environment and not a bug
> per-se. Please describe where and how you're building and running
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/DemocracyOS/app/issues/700#issuecomment-78386947>.
>



-- 
Dany Amoyi
+33 603 223 219

**Comment by fulldanad** [comment]
Hi Mate,

I also tried to install democracyos on a brand new Ubuntu hosted on the
amazon cloud.

The make did a lot of download anf finiched with an error about the node
version.

So tried to upgrade it but it seems I have the latest installed.

Check this :

ubuntu@ip-172-31-32-5:/tmp/app$ sudo apt-get upgrade node
Reading package lists... Done
Building dependency tree
Reading state information... Done
Calculating upgrade... Done
node is already the newest version.
The following packages have been kept back:
  linux-headers-generic linux-headers-virtual linux-image-virtual
  linux-virtual
0 upgraded, 0 newly installed, 0 to remove and 4 not upgraded.
ubuntu@ip-172-31-32-5:/tmp/app$ make
Installing dependencies...
npm WARN package.json co-prompt@1.0.0 No repository field.
npm WARN package.json type-component@0.0.1 No repository field.

> DemocracyOS@0.12.8 postinstall /tmp/app
> node ./bin/dos-install && node ./bin/dos-config && node ./bin/dos-build

npm ERR! weird error 1
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian

npm ERR! not ok code 0
make: *** [packages] Error 1
ubuntu@ip-172-31-32-5:/tmp/app$

ubuntu@ip-172-31-32-5:/tmp/app$
ubuntu@ip-172-31-32-5:/tmp/app$ sudo apt-get upgrade npm
Reading package lists... Done
Building dependency tree
Reading state information... Done
Calculating upgrade... Done
npm is already the newest version.
The following packages have been kept back:
  linux-headers-generic linux-headers-virtual linux-image-virtual
  linux-virtual
0 upgraded, 0 newly installed, 0 to remove and 4 not upgraded.
ubuntu@ip-172-31-32-5:/tmp/app$


Any idea ?

Cheers
Dany

2015-03-12 22:22 GMT+01:00 Dany Amoyi <dany.amoyi@gmail.com>:

> It runs on a synology DS415+
>
>
> bash-3.2# mongod &
> [1] 20046
> bash-3.2# mongod --help for help and startup options
> 2015-03-12T19:14:24.583+0100 [initandlisten] MongoDB starting : pid=20046
> port=27017 dbpath=/data/db 64-bit host=DD
> 2015-03-12T19:14:24.583+0100 [initandlisten] db version v2.6.7
> 2015-03-12T19:14:24.583+0100 [initandlisten] git version:
> a7d57ad27c382de82e9cb93bf983a80fd9ac9899
> 2015-03-12T19:14:24.583+0100 [initandlisten] build info: Linux
> build7.nj1.10gen.cc 2.6.32-431.3.1.el6.x86_64 #1 SMP Fri Jan 3 21:39:27
> UTC 2014 x86_64 BOOST_LIB_VERSION=1_49
> 2015-03-12T19:14:24.583+0100 [initandlisten] allocator: tcmalloc
> 2015-03-12T19:14:24.584+0100 [initandlisten] options: {}
> 2015-03-12T19:14:24.613+0100 [initandlisten]
> 2015-03-12T19:14:24.613+0100 [initandlisten] ** WARNING: Readahead for
> /data/db is set to 2048KB
> 2015-03-12T19:14:24.613+0100 [initandlisten] **          We suggest
> setting it to 256KB (512 sectors) or less
> 2015-03-12T19:14:24.613+0100 [initandlisten] **
> http://dochub.mongodb.org/core/readahead
> 2015-03-12T19:14:24.819+0100 [initandlisten] journal dir=/data/db/journal
> 2015-03-12T19:14:24.834+0100 [initandlisten] recover : no journal files
> present, no recovery needed
> 2015-03-12T19:14:25.239+0100 [initandlisten] waiting for connections on
> port 27017
>
> bash-3.2#
> bash-3.2#
> bash-3.2#
> bash-3.2# make
> Installing dependencies...
> npm WARN package.json passport-local@0.1.6 No README data
> npm WARN package.json co-prompt@1.0.0 No repository field.
> npm WARN package.json t-component@1.0.0 repo should probably be
> repository.
> npm WARN package.json type-component@0.0.1 No repository field.
> npm WARN cannot run in wd DemocracyOS@0.10.11 node ./bin/dos-install
> --config && node ./bin/dos-config && node ./bin/dos-build
> (wd=/volume1/manual_install/democracyos_app)
> Done.\n
> Starting application...
>   democracyos:config Load local configuration from
> /volume1/manual_install/democracyos_app/config/development.json +0ms
>   democracyos:config Merge environment set configuration variables +8ms
>   democracyos:config Loaded config object for env development with sha
> "c8f5e109d6d78ffdd847dce25314c06a" +6ms
> js-bson: Failed to load c++ bson extension, using pure JS version
>   democracyos:config Invalid config key "mongoUsersUrl" +2s
>   democracyos:root Application started on port 3000 +0ms
> 2015-03-12T19:14:36.533+0100 [initandlisten] connection accepted from
> 127.0.0.1:35459 #1 (1 connection now open)
> 2015-03-12T19:14:36.534+0100 [initandlisten] connection accepted from
> 127.0.0.1:35460 #2 (2 connections now open)
> 2015-03-12T19:14:36.537+0100 [initandlisten] connection accepted from
> 127.0.0.1:35461 #3 (3 connections now open)
> 2015-03-12T19:14:36.537+0100 [initandlisten] connection accepted from
> 127.0.0.1:35462 #4 (4 connections now open)
> 2015-03-12T19:14:36.538+0100 [initandlisten] connection accepted from
> 127.0.0.1:35463 #5 (5 connections now open)
> 2015-03-12T19:14:36.538+0100 [initandlisten] connection accepted from
> 127.0.0.1:35464 #6 (6 connections now open)
> 2015-03-12T19:14:36.539+0100 [initandlisten] connection accepted from
> 127.0.0.1:35465 #7 (7 connections now open)
> 2015-03-12T19:14:36.539+0100 [initandlisten] connection accepted from
> 127.0.0.1:35466 #8 (8 connections now open)
> 2015-03-12T19:14:36.540+0100 [initandlisten] connection accepted from
> 127.0.0.1:35467 #9 (9 connections now open)
> 2015-03-12T19:14:36.540+0100 [initandlisten] connection accepted from
> 127.0.0.1:35468 #10 (10 connections now open)
>
>
> Then I launch my webbrowser to access the http://192.168.1.15:3000/
>
>
> And I get a blanck page with DemocracyOS as a title and the following logs.
>
> 2015-03-12T19:15:25.255+0100 [clientcursormon] mem (MB) res:51 virt:524
> 2015-03-12T19:15:25.255+0100 [clientcursormon]  mapped (incl journal
> view):320
> 2015-03-12T19:15:25.255+0100 [clientcursormon]  connections:10
>   democracyos:jwt HTTP header x-access-token has no token. Moving on...
> +0ms
>   democracyos:build Build /app.css. +0ms
>   democracyos:build Build /app.js. +11ms
>   outdated name of a dependency : please update: "guille/ms.js" ->
> "rauchg/ms.js"
>   outdated name of a dependency : please update: "guille/ms.js" ->
> "rauchg/ms.js"
>   outdated name of a dependency : please update: "component/get-document"
> -> "webmodules/get-document"
>   outdated name of a dependency : please update: "component/get-document"
> -> "webmodules/get-document"
>   democracyos:jwt HTTP header x-access-token has no token. Moving on...
> +32s
>
> /volume1/manual_install/democracyos_app/lib/build/index.js:53
>         if (err) throw err;
>                        ^
> Error: failed to read "component~emitter@1.0.0"'s file "index.js"
>     at
> /volume1/manual_install/democracyos_app/node_modules/component-builder/node_modules/component-manifest/build/index.js:440:21
>     at fs.js:207:20
>     at OpenReq.Req.done
> (/volume1/manual_install/democracyos_app/node_modules/component-resolver/node_modules/graceful-fs/graceful-fs.js:143:5)
>     at OpenReq.done
> (/volume1/manual_install/democracyos_app/node_modules/component-resolver/node_modules/graceful-fs/graceful-fs.js:63:22)
>     at OpenReq.Req.done
> (/volume1/manual_install/democracyos_app/node_modules/component-builder/node_modules/graceful-fs/graceful-fs.js:143:5)
>     at OpenReq.done
> (/volume1/manual_install/democracyos_app/node_modules/component-builder/node_modules/graceful-fs/graceful-fs.js:63:22)
>     at Object.oncomplete (fs.js:107:15)
> 2015-03-12T19:16:23.961+0100 [conn1] end connection 127.0.0.1:35459 (9
> connections now open)
> 2015-03-12T19:16:23.961+0100 [conn7] end connection 127.0.0.1:35465 (9
> connections now open)
> 2015-03-12T19:16:23.961+0100 [conn6] end connection 127.0.0.1:35464 (9
> connections now open)
> 2015-03-12T19:16:23.961+0100 [conn3] end connection 127.0.0.1:35461 (9
> connections now open)
> 2015-03-12T19:16:23.961+0100 [conn2] end connection 127.0.0.1:35460 (8
> connections now open)
> 2015-03-12T19:16:23.961+0100 [conn5] end connection 127.0.0.1:35463 (6
> connections now open)
> 2015-03-12T19:16:23.961+0100 [conn4] end connection 127.0.0.1:35462 (9
> connections now open)
> 2015-03-12T19:16:23.962+0100 [conn8] end connection 127.0.0.1:35466 (2
> connections now open)
> 2015-03-12T19:16:23.962+0100 [conn9] end connection 127.0.0.1:35467 (2
> connections now open)
> 2015-03-12T19:16:23.962+0100 [conn10] end connection 127.0.0.1:35468 (2
> connections now open)
> make: *** [run] Error 8
> bash-3.2#
>
>
>
> 2015-03-11 23:30 GMT+01:00 Guido Vilariño <notifications@github.com>:
>
>> This seem like a particular error for your environment and not a bug
>> per-se. Please describe where and how you're building and running
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/DemocracyOS/app/issues/700#issuecomment-78386947>.
>>
>
>
>
> --
> Dany Amoyi
> +33 603 223 219
>



-- 
Dany Amoyi
+33 603 223 219

**Comment by fulldanad** [comment]
I tried sud make to go arrount the "weird error" but no luck : 

ubuntu@ip-172-31-32-5:/tmp/app$ sudo make
Installing dependencies...
npm WARN package.json co-prompt@1.0.0 No repository field.
npm WARN package.json type-component@0.0.1 No repository field.
npm WARN cannot run in wd DemocracyOS@0.12.8 node ./bin/dos-install && node ./bin/dos-config && node ./bin/dos-build (wd=/tmp/app)
Starting application...
make: *** [run] Error 1
ubuntu@ip-172-31-32-5:/tmp/app$

**Comment by jfresco** [comment]
@fulldanad For Ubuntu please install Node from the [Chris Lea's PPA](http://www.ubuntuupdates.org/ppa/chris_lea_nodejs). Installing Node from the default Ubuntu repositories is really weird.
You can also consider using [nvm](https://github.com/creationix/nvm).

**Comment by gvilarino** [comment]
Please let's keep this conversation going in our support channels. A github issue isn't the place for this.
