### ISSUE TITLE
Forbidden access from non-locahost

### ISSUE THREAD

**Issue by LeMarwin** [DemocracyOS/app#709]
Clone app repo, configure development env.
add myself as staff and run
Open browser and enter: localhost:3000
Register with staff e-mail (even verify it).
Create tag, law, add an argument. Logout.
Open new tab, enter %myIP%:3000 (192.168..) or try to access from another PC, either from LAN or not.
Login. After login I can access profile information and see the arguments.
But if I try to do anything: comment, vote etc, I get "{ "error": "Forbidden access", "action": { "redirect": "/login" } }"
I checked logs, it says: "Citizen is not logged in", even though site shows my avatar.
If I refresh the tab, site returns to not-login state
Also log says: "HTTP header x-access-token has no token.", don't know if it's important.

**Comment by NCrashed** [comment]
I have the same issue. It is a blocker issue to use the system.

P.S. I have checked on Fedora 21 and CentOS 7, the problem appears across all browsers (except Opera, wasn't tried).

**Comment by gvilarino** [comment]
We've been seeing some problems lately with this; we'll check it out right away.

@LeMarwin @NCrashed please check your actual running version and fall back to `0.12.7` for the time being if possible; that shouldn't be an issue in that version.

**Comment by NCrashed** [comment]
Version `0.12.7` has the same problem, but error message is different:
```
Error: Origin is not allowed by Access-Control-Allow-Origin
```

**Comment by slifszyc** [comment]
Hi if this is blocking for you please use `0.10.14` release of DemocracyOS.

We'll be working on fixing those issues on the next releases.

**Comment by slifszyc** [comment]
@LeMarwin @NCrashed we have fixed this on https://github.com/DemocracyOS/app/tree/0.13.0

Sorry for the inconvenience!

**Comment by NCrashed** [comment]
Thank you!
