### ISSUE TITLE
Make gravatar calls always via HTTPS

### ISSUE THREAD

**Issue by gvilarino** [DemocracyOS/app#711]
we're seeing TLS warnings because gravatar images aren't been served via HTTP.

**Comment by gvilarino** [comment]
I'd say this shouldn't be done, after all. Gravatars shoul ALWAYS be served via HTTPS, independently from `PROTOCOL` var. Gravatars are always available under HTTPS so we shouldn't care if the `PROTOCOL` env var is set to `http` or `https`. Also, following the env var would prevent hub apps from requesting via `https` since they don't with on `PROTOCOL: https`

**Comment by jfresco** [comment]
That's exactly [what i've done on `hub`](https://github.com/DemocracyOS/hub/commit/1038d54316e3d0145b6c8ce08689579ee1935ee4). I'll do the same here.
I'm changing the issue title to avoid confusions.

**Comment by gvilarino** [comment]
@jfresco please take care of this under `development` so we can close the milestone.
