### ISSUE TITLE
Typo in the "Login or Signup" message

### ISSUE THREAD

**Issue by rafarc21** [DemocracyOS/app#717]
This is a little one, spoted on the feeback.democracyOS.com page 

https://cloudup.com/cec889i4xRI

Not sure if it repeates on other pages.

**Comment by jfresco** [comment]
@rafarc21 Thanks for spotting that. Just to make sure: you refer to the missing spaces between the words  "topic." and "Login", and between "or" and "Signup"?

**Comment by rafarc21** [comment]
Yes, thats it José. Thanks for clarifying.
