### ISSUE TITLE
Mixing up letter I and İ in Turkish when changing "i" to upper case

### ISSUE THREAD

**Issue by hakanerturan** [DemocracyOS/app#718]
"i" and "ı" are two seperate letters in Turkish and both have upper cases ("ı", "I", "i", "İ"). When naming a democracy I used both upper and lower case "i" and it is displayed correctly in the tab header of the browser. However, the name of the democracy displayed next to user name is capitalized and the letters are mixed up. The Upper case İ is correctly transferred, but, lower case "i" is changed to Upper case "I".
  ![capture1](https://cloud.githubusercontent.com/assets/11680202/6868414/24aaf816-d494-11e4-921e-45993bb4f0bc.PNG)

**Comment by jfresco** [comment]
Sorry if I don't get it very well, I'm not familiarized with the turkish alphabet.
You mean that capital "i" (latin alphabet) should have a dot on the top? Or the four letters belongs to the turkish alphabet and one of them is not being displayed correctly?

**Comment by hakanerturan** [comment]
Sorry for the confusion José. Let me try to clarify it;
We have two different letters in Turkish Alphabet "i/İ" and "ı/I", they have different sounds. When naming the new democracy, I used both upper case and lower case "i/İ". The upper case İ is displayed correctly as "İ", but when changing the lower case "i" to upper case, it was transformed into "I" as in English, but actually this is a different sound in Turkish. It is really hard to manage as long as a there is a language detection. Therefore, in my opinion it is better to keep the name of the democracy as it was input without changing the case and displaying it with the case as it was originally input. I hope I didn't make it   more confusing. Cheers, Hakan

**Comment by jfresco** [comment]
Seems to be related to the font we are using. We'll have it in mind when we get rid of #366.

**Comment by gvilarino** [comment]
@hakanerturan can you suggest any ways of verifying that a font supports those characters?

**Comment by hakanerturan** [comment]
@gvilarino Unfortunately, I don't have any suggestions. There are other Turkish specific charaters, but the transition between these "I/ı/İ/i" is a very specific issue. There might be no solution with the fonts unless the language is detected. And best solution would be to keep the name of the democracies created in the system with the original case of each letter (uppercase or lowercase) as it was input by the user. BR,Hakan

**Comment by slifszyc** [comment]
Right now we are using this font. Should be changed on Turkish deployments if it doesn't fit well.
