### ISSUE TITLE
component-install falling over on busy internet - was "tj/debug seems to have been dropped by tj ?"

### ISSUE THREAD

**Issue by AaronNGray** [DemocracyOS/app#725]
I am getting the error :-

    fatal : no remote found for dependency "tj/debug".

On doing a 'make'

I cannot find out what package is dependent upon it either, as the dependent packages seem to be deleted and it means going through them one by one AFAICT

**Comment by AaronNGray** [comment]
https://github.com/visionmedia/debug seems to be the old repo that has not been taken across to tj's and there is some module or modules updated to point to tj/debug !

**Comment by AaronNGray** [comment]
seems to be a reference in app/lib/debug/component.json to tj/debug !

**Comment by AaronNGray** [comment]
I have updated lib/debug/component.json to use visionmedia/debug 

    app\lib\debug> component install visionmedia/debug

but when I do a 'make' it is giving :-

    fatal : no remote found for dependency "mediavision/debug".

Still !

**Comment by AaronNGray** [comment]
I am unable to do the 

     app\lib\debug> component install visionmedia/debug

on Windows as it is giving 

    fatal : no remote found for dependency "mediavision/debug".

Straight away, dunno why there are different behaviours on Windows as to Linux ?

**Comment by elias551** [comment]
Hello Aaron,

It seems like the url [https://github.com/tj/debug] redirects to [https://github.com/visionmedia/debug], so there should be no problem with the url.

Maybe it's not the same problem but I had the same issue with this module while I did not configured the github token in git (this module must be the 61st I guess)

**Comment by AaronNGray** [comment]
Hi Elias,

I could not get https://github.com/tj/debug to resolve at all.

I tried setting up my github token in the :-

     git config --local remote.origin.url ....

But that makes no difference :(

I have just moved lib/debug into a separate test directory as a project in its own right and it works fine !

and

    component install tj/debug

also works fine in the new test directory.

So something is odd, hopefully it is something simple then.

**Comment by AaronNGray** [comment]
Okay going back to the DemocracyOS repo rather than using our UKDemocracyOS repo seems to work fine. Our UK one is an exact fork with no mods and is uptodate so I cannot seem to work out why it is not working now .....

**Comment by AaronNGray** [comment]
Okay its just being non determinate. GitHub was being DDoS'ed apparently and I think its possibly to do with this maybe as some things are now working that were not working before but for no reason. And it seems only to be with new repos, not existing ones.

I think the componentjs component architecture does not do enough retries or wait long enough at times.

**Comment by AaronNGray** [comment]
Okay it works fine when the internet is quiet in both UK and America like 6:00AM GMT in the morning here.
I need to look how component-install works and see if that can be modified not to fall over if there is undue delays at points in the componentjs install process.

**Comment by gvilarino** [comment]
@AaronNGray you can learn [more about `componentjs` here](https://github.com/componentjs/guide/blob/master/component/getting-started.md).

I'm closing this since it isn't a `DemocracyOS` issue.
