### ISSUE TITLE
Cannot complete user registration

### ISSUE THREAD

**Issue by elias551** [DemocracyOS/app#726]
When creating a user from /signup, the user is created in db but an error occurs while sending mail validation

      democracyos:signup new user [5520f4cef58c065c2f7da6bc] from Local signup [user@mail.com] +7ms
      democracyos:signup Saved user [5520f4cef58c065c2f7da6bc] +476ms
      democracyos:db-api:token Creating new email validation token for citizen {"__v":0,"avatar":"http://gravatar.com/avatar/6ad193f57f79ac444c3621370da955e9?d=mm&size=200","email":"user@mail.com","firstName":"aaaa","lastName":"bbbb","_id":"5520f4cef58c065c2f7da6bc","notifications":{"new-topic":false,"replies":true},"createdAt":"2015-04-05T08:39:42.701Z","emailValidated":true,"staff":false,"fullName":"aaaa bbbb","id":"5520f4cef58c065c2f7da6bc"} +0ms
      democracyos:db-api:token Removing all tokens for citizen {"__v":0,"avatar":"http://gravatar.com/avatar/6ad193f57f79ac444c3621370da955e9?d=mm&size=200","email":"user@mail.com","firstName":"aaaa","lastName":"bbbb","_id":"5520f4cef58c065c2f7da6bc","notifications":{"new-topic":false,"replies":true},"createdAt":"2015-04-05T08:39:42.701Z","emailValidated":true,"staff":false,"fullName":"aaaa bbbb","id":"5520f4cef58c065c2f7da6bc"} +1ms
      democracyos:db-api:token Creating new token for citizen {"__v":0,"avatar":"http://gravatar.com/avatar/6ad193f57f79ac444c3621370da955e9?d=mm&size=200","email":"user@mail.com","firstName":"aaaa","lastName":"bbbb","_id":"5520f4cef58c065c2f7da6bc","notifications":{"new-topic":false,"replies":true},"createdAt":"2015-04-05T08:39:42.701Z","emailValidated":true,"staff":false,"fullName":"aaaa bbbb","id":"5520f4cef58c065c2f7da6bc"}, meta {"ip":"::ffff:127.0.0.1","ips":[],"host":"localhost:3000","referer":"http://localhost:3000/signup","ua":"Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:37.0) Gecko/20100101 Firefox/37.0"}, scope email-validation +33ms
      democracyos:db-api:token Delivering token {"__v":0,"user":"5520f4cef58c065c2f7da6bc","scope":"email-validation","meta":{"ua":"Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:37.0) Gecko/20100101 Firefox/37.0","referer":"http://localhost:3000/signup","host":"localhost:3000","ips":[],"ip":"::ffff:127.0.0.1"},"_id":"5520f4cff58c065c2f7da6bd","createdAt":"2015-04-05T08:39:43.214Z"} +32ms
      democracyos:notifications Unable connect to the notifier server - Error: {"code":"ECONNREFUSED","errno":"ECONNREFUSED","syscall":"connect"} +41ms
      democracyos:signup Error when sending notification for event signup to user {"__v":0,"avatar":"http://gravatar.com/avatar/6ad193f57f79ac444c3621370da955e9?d=mm&size=200","email":"user@mail.com","firstName":"aaaa","lastName":"bbbb","_id":"5520f4cef58c065c2f7da6bc","notifications":{"new-topic":false,"replies":true},"createdAt":"2015-04-05T08:39:42.701Z","emailValidated":true,"staff":false,"fullName":"aaaa bbbb","id":"5520f4cef58c065c2f7da6bc"} +0ms

I'm running democracyOS on 
nodejs 0.12.2
mongo 3.0.1
Ubuntu Desktop 14.10

**Comment by elias551** [comment]
Ok my bad, I had no instance of notifier running.

By the way, there is no clue in the installation wiki about the need to have notifier, it should be good to have a section giving a link to this project

**Comment by mjlescano** [comment]
Cool, thanks for the feedback.

Just added the clarification at [Running in production environment](https://github.com/DemocracyOS/app/wiki/Installation#running-in-production-environment).

**Comment by Istenais** [comment]
Can anyone post tutorial on how to run notifier? I've configured config file, but I get the same error as OP.

**Comment by mjlescano** [comment]
Added it as a dependency on the [wiki](https://github.com/DemocracyOS/app/wiki/Installation). Just to let you now, on the incoming versions the notifier will be self-contained on the app, so it wont be necessary to run it on another server.

**Comment by gvilarino** [comment]
Adding to @mjlescano: it won't be necessary but will still be an option.
