### ISSUE TITLE
Signin and signup allows invalid email addresses

### ISSUE THREAD

**Issue by jfresco** [DemocracyOS/app#736]
Gmail provides [aliases](https://support.google.com/mail/answer/12096?hl=en) for each of its accounts. For example, `pepe+1@gmail.com` and `pepe+2@gmail.com` are aliases of `pepe@gmail.com`. With each alias a user can create different accounts on DemocracyOS.
In order to make more robust the identity validation we should get rid of this.

**Comment by mjlescano** [comment]
https://www.npmjs.com/package/verigy

**Comment by mjlescano** [comment]
Things in common with #689
