### ISSUE TITLE
Windows port

### ISSUE THREAD

**Issue by AaronNGray** [DemocracyOS/app#739]
Hi,
We are working on a Windows port of DemocracyOS. Its at a stage where its documented, building, running, but not fully tested.

http://github.com/UKDemocracyOS/app

Instillation instructions are at :-

https://github.com/UKDemocracyOS/app/wiki/Windows-Installation

We are currently preparing things for developers, testing and are dealing with bugs, and working on a parallel online Linux deployment test version.

There are issues, see our issues :-

https://github.com/UKDemocracyOS/app/issues

I can make a pull request as soon as the DemocracyOS team have checked it and think ready for a commit. The changes should not effect functioning of the *nix versions.

**Comment by jfresco** [comment]
Thanks @AaronNGray, we'll take a look. Remember that we report just issues here. To make questions or say something to us, please use the [mailing list](http://groups.google.com/group/democracyos-app).
