### ISSUE TITLE
Share message as an env variable

### ISSUE THREAD

**Issue by slifszyc** [DemocracyOS/app#742]
The default tweet text should be config sensible for each deployment.

**Comment by gvilarino** [comment]
@slifszyc you may check the DEMOS fork for additional stuff on these things. We really customized that one.

**Comment by slifszyc** [comment]
Yeaaaaaaaaaahhh... no, we shouldn't.

https://github.com/Legislatura/demos/blob/demos-phase2/lib/proposal-article/article.jade#L92

**Comment by gvilarino** [comment]
:+1:
