### ISSUE TITLE
admin-laws-form is based on HTML form submit

### ISSUE THREAD

**Issue by AaronNGray** [DemocracyOS/app#753]
`lib/admin-laws-form` is based on an HTML form submit. This wall and probably has caused peoples work to be lost. It needs moving to and AJAX solution.

**Comment by AaronNGray** [comment]
Using AJAX could allow auto save like Gmail's

**Comment by gvilarino** [comment]
We'll provide a solution for this after our `1.0.0` release. I like Github's `localstorage` approach better.

**Comment by slifszyc** [comment]
It doesn't use HTML form submit.

We're currently using [autosubmit](https://github.com/DemocracyOS/app/blob/1.0.0/lib/autosubmit/autosubmit.js) to submit all forms.

Closing this.
