### ISSUE TITLE
Stop using jQuery

### ISSUE THREAD

**Issue by mjlescano** [DemocracyOS/app#758]
It's loaded globally on the layout, and some components use it.

**Comment by mjlescano** [comment]
Closed by #757 
jQuery is still loaded on layout, because list.js needs it.

**Comment by jfresco** [comment]
@mjlescano list.js does not depends on jQuery. See its `component.json`, it only requires jQuery as a development dependency:
```
  "dependencies": {
    "component/classes": "*",
    "segmentio/extend": "*",
    "component/indexof": "*",
    "javve/events": "*",
    "javve/get-by-class": "*",
    "javve/get-attribute": "*",
    "javve/natural-sort": "*",
    "javve/to-string": "*",
    "component/type": "*"
  },
  "development": {
    "dependencies": {
      "visionmedia/mocha": "*",
      "techjacker/expect.js": "*",
      "component/jquery": "1.9.1"
    }
```

**Comment by gvilarino** [comment]
@mjlescano remove `jQuery` from layout and close this pls

**Comment by slifszyc** [comment]
jQuery is [required](https://github.com/aroc/side-comments/blob/d7fd92a9f75fed8dc4bb92c03461adf63ef255b1/README.md#2-include-sidecommentsjs-in-your-project) to use [SideComments](https://github.com/DemocracyOS/side-comments)

**Comment by slifszyc** [comment]
We won't stop using [SideCommnets](https://github.com/DemocracyOS/side-comments) on the near future, we should rewrite that repo to remove jQuery dep
