### ISSUE TITLE
Refactor configuration files

### ISSUE THREAD

**Issue by mjlescano** [DemocracyOS/app#762]
Base configuration file will be `/config/defaults.json`. Then, optionaly, overriden by `/config/{environment}.json`. And finally overriden by the `ENV vars` that exist.

`/config/defaults.json`: Will be used as reference to enforce which `vars` exists and what `type` have.

`/lib/config/client.js`: It won't be builded anymore. It will be generated dynamically and "pasted" on the layout.

**Comment by gvilarino** [comment]
Related: #731

**Comment by mjlescano** [comment]
Also, all keys on `.json` files should be `camelCase`.

**Comment by AaronNGray** [comment]
Theres a spurious error message being thrown up by
lib/config/index.js:config() on startup its looking for the MongoUsersUrl :-

    democracyos:config Invaild config key "mongoUsersUrl"

If 'MongoUsersUrl' is not defined in the config file.

This needs quieting if you are dealing with this area. maybe a silent:bool
flag on config() ?

**Comment by gvilarino** [comment]
@AaronNGray don't worry about that; they're just warnings of some values that *could* be there and aren't defined. The refactor will change that.

**Comment by AaronNGray** [comment]
It wasted me an hour !
