### ISSUE TITLE
MongoHQ sandbox in heroku gives error

### ISSUE THREAD

**Issue by rdgutierrez** [DemocracyOS/app#771]
When i use the command "heroku addons:add mongohq:sandbox" i get this error 
 !    Add-on plan not found.

If i use the "heroku addons:add mongohq" and all works fine, is the same? of course this command set a 18$ month plan

**Comment by rdgutierrez** [comment]
I´m following this tutorial https://github.com/DemocracyOS/app/wiki/How-to-deploy-to-Heroku , but i´m missing this step  "Add the config variables needed for the app to work using heroku config:set VAR_NAME=VALUE VAR_NAME2=VALUE2 etc." have you some sample of this for heroku?

**Comment by gvilarino** [comment]
Updated it to mongolab. MongoHQ is no longer a compatible addon

**Comment by rdgutierrez** [comment]
Thanks Guido
