### ISSUE TITLE
fatal : no remote found for dependency "marcuswestin/store .js".

### ISSUE THREAD

**Issue by rdgutierrez** [DemocracyOS/app#772]
I can´t make the "git push heroku master" i receive several errors and the build fails.

THIS IS THE LOG

remote:        build directory...
remote:        cache directory...
remote:        environment variables...
remote:
remote:        Node engine:         0.10.x
remote:        Npm engine:          unspecified
remote:        Start mechanism:     Procfile
remote:        node_modules source: package.json
remote:        node_modules cached: false
remote:
remote:        NPM_CONFIG_PRODUCTION=true
remote:        NODE_MODULES_CACHE=true
remote:
remote: -----> Installing binaries
remote:        Resolving node version 0.10.x via semver.io...
remote:        Downloading and installing node 0.10.38...
remote:        Using default npm version: 1.4.28
remote:
remote: -----> Building dependencies
remote:        No cache available
remote:        Installing node modules
remote:
remote:        > kerberos@0.0.9 install /tmp/build_2cc6453d41d5c21b00cdbb578dd25
9d7/node_modules/mongoose/node_modules/mongodb/node_modules/kerberos
remote:        > (node-gyp rebuild 2> builderror.log) || (exit 0)
remote:
remote:        make: Entering directory `/tmp/build_2cc6453d41d5c21b00cdbb578dd2
59d7/node_modules/mongoose/node_modules/mongodb/node_modules/kerberos/build'
remote:          CXX(target) Release/obj.target/kerberos/lib/kerberos.o
remote:          CXX(target) Release/obj.target/kerberos/lib/worker.o
remote:          CC(target) Release/obj.target/kerberos/lib/kerberosgss.o
remote:          CC(target) Release/obj.target/kerberos/lib/base64.o
remote:          CXX(target) Release/obj.target/kerberos/lib/kerberos_context.o
remote:          SOLINK_MODULE(target) Release/obj.target/kerberos.node
remote:          SOLINK_MODULE(target) Release/obj.target/kerberos.node: Finishe
d
remote:          COPY Release/kerberos.node
remote:        make: Leaving directory `/tmp/build_2cc6453d41d5c21b00cdbb578dd25
9d7/node_modules/mongoose/node_modules/mongodb/node_modules/kerberos/build'
remote:
remote:        > bson@0.2.21 install /tmp/build_2cc6453d41d5c21b00cdbb578dd259d7
/node_modules/mongoose/node_modules/mongodb/node_modules/bson
remote:        > (node-gyp rebuild 2> builderror.log) || (exit 0)
remote:
remote:        make: Entering directory `/tmp/build_2cc6453d41d5c21b00cdbb578dd2
59d7/node_modules/mongoose/node_modules/mongodb/node_modules/bson/build'
remote:          CXX(target) Release/obj.target/bson/ext/bson.o
remote:          SOLINK_MODULE(target) Release/obj.target/bson.node
remote:          SOLINK_MODULE(target) Release/obj.target/bson.node: Finished
remote:          COPY Release/bson.node
remote:        make: Leaving directory `/tmp/build_2cc6453d41d5c21b00cdbb578dd25
9d7/node_modules/mongoose/node_modules/mongodb/node_modules/bson/build'
remote:
remote:        > DemocracyOS@0.14.0 postinstall /tmp/build_2cc6453d41d5c21b00cdb
b578dd259d7
remote:        > node ./bin/dos-install && node ./bin/dos-config && node ./bin/d
os-build
remote:
remote:
remote:           installed : code42day/ga@1.1.0 in 280ms
remote:           installed : democracyos/timeago@master in 296ms
remote:           installed : visionmedia/page.js@1.3.7 in 309ms
remote:           installed : component/t@1.0.0 in 312ms
remote:           installed : slifszyc/query@0.0.3 in 165ms
remote:           installed : component/dom@0.7.1 in 261ms
remote:           installed : component/classes@1.2.0 in 273ms
remote:           installed : cristiandouce/loading-lock@0.0.2 in 319ms
remote:           installed : jadejs/jade@1.1.5 in 205ms
remote:           installed : yields/empty@0.0.1 in 174ms
remote:           installed : component/events@1.0.9 in 159ms
remote:           installed : component/domify@1.3.1 in 224ms
remote:           installed : component/emitter@1.1.3 in 255ms
remote:           installed : segmentio/submit-form@0.0.1 in 188ms
remote:           installed : tj/node-querystring@0.6.6 in 243ms
remote:           installed : yields/serialize@0.2.0 in 240ms
remote:           installed : democracyos/headroom.js@0.7.1 in 233ms
remote:           installed : component/emitter@1.1.1 in 321ms
remote:           installed : component/cookie@1.1.1 in 242ms
remote:           installed : component/closest@0.1.4 in 481ms
remote:
remote:
remote:        github remote: 58 of 60 requests remaining, resetting at Thu Apr
23 2015 18:29:07 GMT+0000 (UTC)
remote:        github remote: see https://github.com/component/guide/blob/master
/changelogs/1.0.0.md#required-authentication for more information.
remote:        github remote: 59 of 60 requests remaining, resetting at Thu Apr
23 2015 18:29:07 GMT+0000 (UTC)
remote:        github remote: see https://github.com/component/guide/blob/master
/changelogs/1.0.0.md#required-authentication for more information.
remote:        github remote: 56 of 60 requests remaining, resetting at Thu Apr
23 2015 18:29:07 GMT+0000 (UTC)
remote:        github remote: see https://github.com/component/guide/blob/master
/changelogs/1.0.0.md#required-authentication for more information.
remote:        github remote: 57 of 60 requests remaining, resetting at Thu Apr
23 2015 18:29:07 GMT+0000 (UTC)
remote:        github remote: see https://github.com/component/guide/blob/master
/changelogs/1.0.0.md#required-authentication for more information.
remote:        github remote: 55 of 60 requests remaining, resetting at Thu Apr
23 2015 18:29:07 GMT+0000 (UTC)
remote:        github remote: see https://github.com/component/guide/blob/master
/changelogs/1.0.0.md#required-authentication for more information.
remote:        github remote: 54 of 60 requests remaining, resetting at Thu Apr
23 2015 18:29:07 GMT+0000 (UTC)
remote:        github remote: see https://github.com/component/guide/blob/master
/changelogs/1.0.0.md#required-authentication for more information.
remote:        github remote: 53 of 60 requests remaining, resetting at Thu Apr
23 2015 18:29:07 GMT+0000 (UTC)
remote:        github remote: see https://github.com/component/guide/blob/master
/changelogs/1.0.0.md#required-authentication for more information.
remote:        github remote: 52 of 60 requests remaining, resetting at Thu Apr
23 2015 18:29:07 GMT+0000 (UTC)
remote:        github remote: see https://github.com/component/guide/blob/master
/changelogs/1.0.0.md#required-authentication for more information.
remote:        github remote: 51 of 60 requests remaining, resetting at Thu Apr
23 2015 18:29:07 GMT+0000 (UTC)
remote:        github remote: see https://github.com/component/guide/blob/master
/changelogs/1.0.0.md#required-authentication for more information.
remote:        github remote: 50 of 60 requests remaining, resetting at Thu Apr
23 2015 18:29:07 GMT+0000 (UTC)
remote:        github remote: see https://github.com/component/guide/blob/master
/changelogs/1.0.0.md#required-authentication for more information.
remote:        github remote: 45 of 60 requests remaining, resetting at Thu Apr
23 2015 18:29:07 GMT+0000 (UTC)
remote:        github remote: see https://github.com/component/guide/blob/master
/changelogs/1.0.0.md#required-authentication for more information.
remote:        github remote: 44 of 60 requests remaining, resetting at Thu Apr
23 2015 18:29:07 GMT+0000 (UTC)
remote:        github remote: see https://github.com/component/guide/blob/master
/changelogs/1.0.0.md#required-authentication for more information.
remote:        github remote: 43 of 60 requests remaining, resetting at Thu Apr
23 2015 18:29:07 GMT+0000 (UTC)
remote:        github remote: see https://github.com/component/guide/blob/master
/changelogs/1.0.0.md#required-authentication for more information.
remote:        github remote: 41 of 60 requests remaining, resetting at Thu Apr
23 2015 18:29:07 GMT+0000 (UTC)
remote:        github remote: see https://github.com/component/guide/blob/master
/changelogs/1.0.0.md#required-authentication for more information.
remote:        github remote: 40 of 60 requests remaining, resetting at Thu Apr
23 2015 18:29:07 GMT+0000 (UTC)
remote:        github remote: see https://github.com/component/guide/blob/master
/changelogs/1.0.0.md#required-authentication for more information.
remote:        github remote: 39 of 60 requests remaining, resetting at Thu Apr
23 2015 18:29:07 GMT+0000 (UTC)
remote:        github remote: see https://github.com/component/guide/blob/master
/changelogs/1.0.0.md#required-authentication for more information.
remote:        github remote: 37 of 60 requests remaining, resetting at Thu Apr
23 2015 18:29:07 GMT+0000 (UTC)
remote:        github remote: see https://github.com/component/guide/blob/master
/changelogs/1.0.0.md#required-authentication for more information.
remote:        github remote: 33 of 60 requests remaining, resetting at Thu Apr
23 2015 18:29:07 GMT+0000 (UTC)
remote:        github remote: see https://github.com/component/guide/blob/master
/changelogs/1.0.0.md#required-authentication for more information.
remote:        github remote: 32 of 60 requests remaining, resetting at Thu Apr
23 2015 18:29:07 GMT+0000 (UTC)
remote:        github remote: see https://github.com/component/guide/blob/master
/changelogs/1.0.0.md#required-authentication for more information.
remote:        github remote: 31 of 60 requests remaining, resetting at Thu Apr
23 2015 18:29:07 GMT+0000 (UTC)
remote:        github remote: see https://github.com/component/guide/blob/master
/changelogs/1.0.0.md#required-authentication for more information.
remote:        github remote: 30 of 60 requests remaining, resetting at Thu Apr
23 2015 18:29:07 GMT+0000 (UTC)
remote:        github remote: see https://github.com/component/guide/blob/master
/changelogs/1.0.0.md#required-authentication for more information.
remote:        github remote: 28 of 60 requests remaining, resetting at Thu Apr
23 2015 18:29:07 GMT+0000 (UTC)
remote:        github remote: see https://github.com/component/guide/blob/master
/changelogs/1.0.0.md#required-authentication for more information.
remote:        github remote: 26 of 60 requests remaining, resetting at Thu Apr
23 2015 18:29:07 GMT+0000 (UTC)
remote:        github remote: see https://github.com/component/guide/blob/master
/changelogs/1.0.0.md#required-authentication for more information.
remote:        github remote: 24 of 60 requests remaining, resetting at Thu Apr
23 2015 18:29:07 GMT+0000 (UTC)
remote:        github remote: see https://github.com/component/guide/blob/master
/changelogs/1.0.0.md#required-authentication for more information.
remote:        github remote: 23 of 60 requests remaining, resetting at Thu Apr
23 2015 18:29:07 GMT+0000 (UTC)
remote:        github remote: see https://github.com/component/guide/blob/master
/changelogs/1.0.0.md#required-authentication for more information.
remote:        github remote: 22 of 60 requests remaining, resetting at Thu Apr
23 2015 18:29:07 GMT+0000 (UTC)
remote:        github remote: see https://github.com/component/guide/blob/master
/changelogs/1.0.0.md#required-authentication for more information.
remote:        github remote: 20 of 60 requests remaining, resetting at Thu Apr
23 2015 18:29:07 GMT+0000 (UTC)
remote:        github remote: see https://github.com/component/guide/blob/master
/changelogs/1.0.0.md#required-authentication for more information.
remote:        github remote: 19 of 60 requests remaining, resetting at Thu Apr
23 2015 18:29:07 GMT+0000 (UTC)
remote:        github remote: see https://github.com/component/guide/blob/master
/changelogs/1.0.0.md#required-authentication for more information.
remote:        github remote: 16 of 60 requests remaining, resetting at Thu Apr
23 2015 18:29:07 GMT+0000 (UTC)
remote:        github remote: see https://github.com/component/guide/blob/master
/changelogs/1.0.0.md#required-authentication for more information.
remote:        github remote: 15 of 60 requests remaining, resetting at Thu Apr
23 2015 18:29:07 GMT+0000 (UTC)
remote:        github remote: see https://github.com/component/guide/blob/master
/changelogs/1.0.0.md#required-authentication for more information.
remote:        github remote: 14 of 60 requests remaining, resetting at Thu Apr
23 2015 18:29:07 GMT+0000 (UTC)
remote:        github remote: see https://github.com/component/guide/blob/master
/changelogs/1.0.0.md#required-authentication for more information.
remote:        github remote: 13 of 60 requests remaining, resetting at Thu Apr
23 2015 18:29:07 GMT+0000 (UTC)
remote:        github remote: see https://github.com/component/guide/blob/master
/changelogs/1.0.0.md#required-authentication for more information.
remote:        github remote: 12 of 60 requests remaining, resetting at Thu Apr
23 2015 18:29:07 GMT+0000 (UTC)
remote:        github remote: see https://github.com/component/guide/blob/master
/changelogs/1.0.0.md#required-authentication for more information.
remote:        github remote: 11 of 60 requests remaining, resetting at Thu Apr
23 2015 18:29:07 GMT+0000 (UTC)
remote:        github remote: see https://github.com/component/guide/blob/master
/changelogs/1.0.0.md#required-authentication for more information.
remote:        github remote: 8 of 60 requests remaining, resetting at Thu Apr 2
3 2015 18:29:07 GMT+0000 (UTC)
remote:        github remote: see https://github.com/component/guide/blob/master
/changelogs/1.0.0.md#required-authentication for more information.
remote:        github remote: 7 of 60 requests remaining, resetting at Thu Apr 2
3 2015 18:29:07 GMT+0000 (UTC)
remote:        github remote: see https://github.com/component/guide/blob/master
/changelogs/1.0.0.md#required-authentication for more information.
remote:        github remote: 5 of 60 requests remaining, resetting at Thu Apr 2
3 2015 18:29:07 GMT+0000 (UTC)
remote:        github remote: see https://github.com/component/guide/blob/master
/changelogs/1.0.0.md#required-authentication for more information.
remote:        github remote: 3 of 60 requests remaining, resetting at Thu Apr 2
3 2015 18:29:07 GMT+0000 (UTC)
remote:        github remote: see https://github.com/component/guide/blob/master
/changelogs/1.0.0.md#required-authentication for more information.
remote:        github remote: 2 of 60 requests remaining, resetting at Thu Apr 2
3 2015 18:29:07 GMT+0000 (UTC)
remote:        github remote: see https://github.com/component/guide/blob/master
/changelogs/1.0.0.md#required-authentication for more information.
remote:        github remote: 1 of 60 requests remaining, resetting at Thu Apr 2
3 2015 18:29:07 GMT+0000 (UTC)
remote:        github remote: see https://github.com/component/guide/blob/master
/changelogs/1.0.0.md#required-authentication for more information.
remote:
remote:               fatal : no remote found for dependency "marcuswestin/store
.js".
remote:
remote:
remote:
remote:        npm ERR! DemocracyOS@0.14.0 postinstall: `node ./bin/dos-install
&& node ./bin/dos-config && node ./bin/dos-build`
remote:        npm ERR! Exit status 1
remote:        npm ERR!
remote:        npm ERR! Failed at the DemocracyOS@0.14.0 postinstall script.
remote:        npm ERR! This is most likely a problem with the DemocracyOS packa
ge,
remote:        npm ERR! not with npm itself.
remote:        npm ERR! Tell the author that this fails on your system:
remote:        npm ERR!     node ./bin/dos-install && node ./bin/dos-config && n
ode ./bin/dos-build
remote:        npm ERR! You can get their info via:
remote:        npm ERR!     npm owner ls DemocracyOS
remote:        npm ERR! There is likely additional logging output above.
remote:        npm ERR! System Linux 3.13.0-49-generic
remote:        npm ERR! command "/tmp/build_2cc6453d41d5c21b00cdbb578dd259d7/.he
roku/node/bin/node" "/tmp/build_2cc6453d41d5c21b00cdbb578dd259d7/.heroku/node/bi
n/npm" "install" "--unsafe-perm" "--quiet" "--userconfig" "/tmp/build_2cc6453d41
d5c21b00cdbb578dd259d7/.npmrc"
remote:        npm ERR! cwd /tmp/build_2cc6453d41d5c21b00cdbb578dd259d7
remote:        npm ERR! node -v v0.10.38
remote:        npm ERR! npm -v 1.4.28
remote:        npm ERR! code ELIFECYCLE
remote:        npm ERR!
remote:        npm ERR! Additional logging details can be found in:
remote:        npm ERR!     /tmp/build_2cc6453d41d5c21b00cdbb578dd259d7/npm-debu
g.log
remote:        npm ERR! not ok code 0
remote:
remote: -----> Build failed
remote:
remote:        We're sorry this build is failing! If you can't find the issue in
 application code,
remote:        please submit a ticket so we can help: https://help.heroku.com/
remote:        You can also try reverting to our legacy Node.js buildpack:
remote:        heroku config:set BUILDPACK_URL=https://github.com/heroku/heroku-
buildpack-nodejs#v63
remote:
remote:        Love,
remote:        Heroku
remote:
remote:  !     Push rejected, failed to compile Node.js app
remote:
remote: Verifying deploy...
remote:
remote: !       Push rejected to democracia-colombia.
remote:
To https://git.heroku.com/democracia-colombia.git
 ! [remote rejected] master -> master (pre-receive hook declined)
error: failed to push some refs to 'https://git.heroku.com/democracia-colombia.g
it'

**Comment by gvilarino** [comment]
Please read our [contribution guidelines](https://github.com/DemocracyOS/app/blob/development/CONTRIBUTING.md) before opening an issue. This isn't a bug or a feature request but a build error on your environment; hence it's inappropriate to open an issue. Refer to our mailing list or gitter channel for assistance.
