### ISSUE TITLE
Error: failed to read "component~emitter@1.0.0"'s

### ISSUE THREAD

**Issue by jesseparker** [DemocracyOS/app#774]
Hi, guys.  Trying to get a demo working and trying to learn npm and component.js on the fly.  Think I'm having dependency problems, but can't figure them out.  Trying to build from HEAD with the nodejs from Chris Lea on Ubuntu 14.02.  On the first request, the component-emitter error is thrown, and also Error: failed to read "cristiandouce~loading-lock@0.1.0"'s file "loading-lock.css".

I've done checkouts to a few of your previous releases, and I get the same kinds of errors - runtime errors about missing dependencies.

If you have some pointers about how to get this sorted out let me know.  I've use several frameworks in the past bud node is new to me.  Thanks.

root@ip-10-183-228-36:~/app# node -v
v0.10.38
root@ip-10-183-228-36:~/app# npm -v
1.4.28
root@ip-10-183-228-36:~/app# git pull
remote: Counting objects: 14, done.
remote: Compressing objects: 100% (13/13), done.
remote: Total 14 (delta 4), reused 0 (delta 0), pack-reused 1
Unpacking objects: 100% (14/14), done.
From https://github.com/DemocracyOS/app
   1569070..d3c3e26  refactor-config -> origin/refactor-config
Already up-to-date.
root@ip-10-183-228-36:~/app# 
root@ip-10-183-228-36:~/app# make clean
Removing dependencies, components and built assets.
Done.

root@ip-10-183-228-36:~/app# make
Installing dependencies...
 
> kerberos@0.0.9 install /root/app/node_modules/mongoose/node_modules/mongodb/node_modules/kerberos
> (node-gyp rebuild 2> builderror.log) || (exit 0)

make[1]: Entering directory `/root/app/node_modules/mongoose/node_modules/mongodb/node_modules/kerberos/build'
  CXX(target) Release/obj.target/kerberos/lib/kerberos.o
make[1]: Leaving directory `/root/app/node_modules/mongoose/node_modules/mongodb/node_modules/kerberos/build'
 
> bson@0.2.21 install /root/app/node_modules/mongoose/node_modules/mongodb/node_modules/bson
> (node-gyp rebuild 2> builderror.log) || (exit 0)

make[1]: Entering directory `/root/app/node_modules/mongoose/node_modules/mongodb/node_modules/bson/build'
  CXX(target) Release/obj.target/bson/ext/bson.o
  SOLINK_MODULE(target) Release/obj.target/bson.node
  SOLINK_MODULE(target) Release/obj.target/bson.node: Finished
  COPY Release/bson.node
make[1]: Leaving directory `/root/app/node_modules/mongoose/node_modules/mongodb/node_modules/bson/build'
npm WARN cannot run in wd DemocracyOS@0.14.0 node ./bin/dos-install && node ./bin/dos-config && node ./bin/dos-build (wd=/root/app)
strip@0.0.7 node_modules/strip

node-path@0.0.3 node_modules/node-path

truncate@1.0.4 node_modules/truncate

type-component@0.0.1 node_modules/type-component

batch@0.5.2 node_modules/batch

passport-local-mongoose@0.2.6 node_modules/passport-local-mongoose

t-component@1.0.0 node_modules/t-component

nowww@1.1.3 node_modules/nowww

express-sslify@0.1.1 node_modules/express-sslify

mongoose-gravatar@0.3.0 node_modules/mongoose-gravatar

commander@2.0.0 node_modules/commander

mongoose-voting@0.1.1 node_modules/mongoose-voting

jwt-simple@0.2.0 node_modules/jwt-simple

builder-jade@1.0.1 node_modules/builder-jade

marked@0.2.10 node_modules/marked

rework-vars@2.0.3 node_modules/rework-vars
└── rework-visit@1.0.0

cookie-parser@1.3.3 node_modules/cookie-parser
├── cookie@0.1.2
└── cookie-signature@1.0.5

co-prompt@1.0.0 node_modules/co-prompt
└── keypress@0.2.1

merge-util@0.3.1 node_modules/merge-util
└── is-empty@0.0.1

bowser@0.7.2 node_modules/bowser

democracyos-db@0.0.1 node_modules/democracyos-db
└── muri@1.0.0

debug@2.1.3 node_modules/debug
└── ms@0.7.0

passport-local@0.1.6 node_modules/passport-local
└── pkginfo@0.2.3

rework-math@1.0.1 node_modules/rework-math
└── rework-visit@1.0.0

arr-diff@1.0.1 node_modules/arr-diff
└── array-slice@0.2.3

cors@2.5.3 node_modules/cors
└── vary@1.0.0

rework-shade@1.4.3 node_modules/rework-shade
├── color-parser@0.1.0
├── rework-visit@1.0.0
└── color-convert@0.3.4

nomnom@1.8.1 node_modules/nomnom
├── chalk@0.4.0 (has-color@0.1.7, ansi-styles@1.0.0, strip-ansi@0.1.1)
└── underscore@1.6.0

mkdirp@0.5.0 node_modules/mkdirp
└── minimist@0.0.8

passport@0.1.18 node_modules/passport
├── pause@0.0.1
└── pkginfo@0.2.3

http-auth@1.3.0 node_modules/http-auth
└── node-uuid@1.4.1

json-file-plus@2.0.0 node_modules/json-file-plus
├── is@2.0.2
├── node.extend@1.1.3 (is@2.1.0)
└── promiseback@2.0.1 (promise-deferred@2.0.1)

notifier-client@0.2.0 node_modules/notifier-client
├── object-component@0.0.3
├── debug@1.0.4 (ms@0.6.2)
└── superagent@0.18.2 (extend@1.2.1, qs@0.6.6, methods@1.0.1, cookiejar@2.0.1, component-emitter@1.1.2, reduce-component@1.0.1, mime@1.2.11, readable-stream@1.0.27-1, form-data@0.1.3, formidable@1.0.14)

google-translate@0.1.8 node_modules/google-translate
├── underscore@1.7.0
├── async@0.9.0
├── he@0.5.0
└── request@2.51.0 (caseless@0.8.0, json-stringify-safe@5.0.0, forever-agent@0.5.2, aws-sign2@0.5.0, stringstream@0.0.4, oauth-sign@0.5.0, tunnel-agent@0.4.0, node-uuid@1.4.3, qs@2.3.3, mime-types@1.0.2, combined-stream@0.0.7, bl@0.9.4, form-data@0.2.0, http-signature@0.10.1, tough-cookie@0.13.0, hawk@1.1.1)

stylus@0.48.1 node_modules/stylus
├── css-parse@1.7.0
├── mkdirp@0.3.5
├── glob@3.2.11 (inherits@2.0.1, minimatch@0.3.0)
├── source-map@0.1.43 (amdefine@0.1.0)
└── sax@0.5.8

imap@0.8.14 node_modules/imap
├── utf7@1.0.0
└── readable-stream@1.1.13 (isarray@0.0.1, string_decoder@0.10.31, core-util-is@1.0.1, inherits@2.0.1)

transliteration@0.1.1 node_modules/transliteration

moment@2.9.0 node_modules/moment

component-stylus-plugin@0.3.1 node_modules/component-stylus-plugin
├── debug@0.7.4
└── stylus@0.43.1 (css-parse@1.7.0, mkdirp@0.3.5, glob@3.2.11, sax@0.5.8)

jade@1.6.0 node_modules/jade
├── character-parser@1.2.0
├── commander@2.1.0
├── void-elements@1.0.0
├── constantinople@2.0.1 (uglify-js@2.4.20)
├── monocle@1.1.51 (readdirp@0.2.5)
├── with@3.0.1 (uglify-js@2.4.20)
└── transformers@2.1.0 (promise@2.0.0, css@1.0.8, uglify-js@2.2.5)

component-builder@1.2.0 node_modules/component-builder
├── co@3.1.0
├── generator-supported@0.0.1
├── cp@0.1.1
├── component-require2@1.1.1
├── requires@1.0.2
├── graceful-fs@2.0.3
├── mkdirp@0.3.5
├── chanel@2.2.0 (to-descriptor@1.0.1)
├── component-flatten@1.0.1 (semver@2.3.2)
├── component-manifest@1.0.0 (unglob@0.1.2)
└── syntax-error@1.1.2 (acorn@0.9.0)

express@3.4.8 node_modules/express
├── methods@0.1.0
├── merge-descriptors@0.0.1
├── debug@0.8.1
├── cookie-signature@1.0.1
├── range-parser@0.0.4
├── fresh@0.2.0
├── buffer-crc32@0.2.1
├── cookie@0.1.0
├── commander@1.3.2 (keypress@0.1.0)
├── mkdirp@0.3.5
├── send@0.1.4 (mime@1.2.11)
└── connect@2.12.0 (uid2@0.0.3, pause@0.0.1, qs@0.6.6, bytes@0.2.1, raw-body@1.1.2, batch@0.5.0, negotiator@0.3.0, multiparty@2.2.0)

mongoose@3.8.24 node_modules/mongoose
├── regexp-clone@0.0.1
├── sliced@0.0.5
├── muri@0.3.1
├── hooks@0.2.1
├── mpath@0.1.1
├── mpromise@0.4.3
├── ms@0.1.0
├── mquery@0.8.0 (debug@0.7.4)
└── mongodb@1.4.31 (readable-stream@1.0.33, kerberos@0.0.9, bson@0.2.21)

component@1.1.0 node_modules/component
├── component-flatten@1.0.1
├── co@3.1.0
├── component-consoler@2.0.0
├── win-fork@1.1.1
├── component-outdated2@1.0.5 (generator-supported@0.0.1)
├── mkdirp@0.3.5
├── component-ls@2.1.0 (archy@0.0.2)
├── component-updater@1.0.5 (generator-supported@0.0.1)
├── commander@2.8.0 (graceful-readlink@1.0.1)
├── component-pin@1.0.5 (generator-supported@0.0.1)
├── semver@2.3.2
├── component-watcher@1.0.3 (sane@0.8.1)
├── rimraf@2.3.2 (glob@4.5.3)
├── tiny-lr-fork@0.0.5 (debug@0.7.4, faye-websocket@0.4.4, noptify@0.0.3, qs@0.5.6)
├── superagent@0.17.0 (methods@0.0.1, extend@1.2.1, cookiejar@1.3.0, qs@0.6.5, debug@0.7.4, emitter-component@1.0.0, reduce-component@1.0.1, mime@1.2.5, formidable@1.0.14)
├── component-resolver@1.3.0 (generator-supported@0.0.1, component-validator@1.1.1, graceful-fs@2.0.3, chanel@2.2.0, unglob@0.1.2, component-downloader@1.2.0)
├── component-build@1.2.2 (builder-es6-module-to-cjs@1.1.0, builder-autoprefixer@1.0.4)
├── component-search2@1.1.1 (stream-to-array@1.0.0, bytes@0.3.0, generator-supported@0.0.1, event-stream@3.3.0, JSONStream@0.8.4, cogent@0.4.3)
└── component-remotes@1.2.0 (generator-supported@0.0.1, component-validator@1.1.1, graceful-fs@2.0.3, cogent@0.4.3-fix-redirects)

component-resolver@1.2.4 node_modules/component-resolver
├── generator-supported@0.0.1
├── component-flatten@1.0.1
├── co@3.1.0
├── component-consoler@2.0.0
├── component-validator@1.1.1
├── graceful-fs@2.0.3
├── chanel@2.2.0 (to-descriptor@1.0.1)
├── semver@2.3.2
├── unglob@0.1.2 (minimatch@0.2.14, glob@3.2.11)
├── component-downloader@1.2.0 (write-to@1.1.1, mkdirp@0.3.5, rimraf@2.3.2, decompress@0.2.5)
├── cogent@0.4.3 (statuses@1.2.1, netrc@0.1.3, write-to@1.1.1, raw-body@1.3.4, proxy-agent@1.1.0)
└── component-remotes@1.2.0 (cogent@0.4.3-fix-redirects)
Starting application...
  democracyos:config Load local configuration from /root/app/config/development.json +0ms
  democracyos:config Merge environment set configuration variables +4ms
  democracyos:config Loaded config object for env development with sha "f8a2fd53084af95a7c5dec9ea26919f7" +2ms
  democracyos:config Invalid config key "mongoUsersUrl" +322ms
  democracyos:db Using mongodb hosts: localhost:27017 +34ms
  democracyos:db Using mongodb URI: mongodb://localhost:27017/DemocracyOS-dev +1ms
  democracyos:db Connecting to MongoDB database DemocracyOS-dev +2ms
  democracyos:root Application started on port 3000 +2s
  democracyos:db Connected to MongoDB on URI: mongodb://localhost:27017/DemocracyOS-dev +22ms
  democracyos:db Connection to MongoDB is now OPEN on URI: mongodb://localhost:27017/DemocracyOS-dev +12ms
  democracyos:jwt HTTP header x-access-token has no token. Moving on... +9s
  democracyos:build Start assets compilation +325ms
  democracyos:build Start assets compilation +12ms
  outdated name of a dependency : please update: "tj/debug" -> "visionmedia/debug"
  outdated name of a dependency : please update: "tj/debug" -> "visionmedia/debug"
  democracyos:build Found error building scripts +9s
  democracyos:build Found error compiling assets: Error: failed to read "component~emitter@1.0.0"'s file "index.js" +1ms
Error: failed to read "component~emitter@1.0.0"'s file "index.js"
    at /root/app/node_modules/component-builder/node_modules/component-manifest/build/index.js:440:21
    at fs.js:208:20
    at OpenReq.Req.done (/root/app/node_modules/component-resolver/node_modules/graceful-fs/graceful-fs.js:143:5)
    at OpenReq.done (/root/app/node_modules/component-resolver/node_modules/graceful-fs/graceful-fs.js:63:22)
    at OpenReq.Req.done (/root/app/node_modules/component-builder/node_modules/graceful-fs/graceful-fs.js:143:5)
    at OpenReq.done (/root/app/node_modules/component-builder/node_modules/graceful-fs/graceful-fs.js:63:22)
    at Object.oncomplete (fs.js:108:15)
  democracyos:build Found error building styles: Error: failed to read "cristiandouce~loading-lock@0.1.0"'s file "loading-lock.css" +45ms
  democracyos:build Files copied successfully +13ms
  democracyos:build Found error building scripts +1s
  democracyos:build Found error compiling assets: Error: failed to read "component~emitter@1.0.0"'s file "index.js" +0ms
Error: failed to read "component~emitter@1.0.0"'s file "index.js"
    at /root/app/node_modules/component-builder/node_modules/component-manifest/build/index.js:440:21
    at fs.js:208:20
    at OpenReq.Req.done (/root/app/node_modules/component-resolver/node_modules/graceful-fs/graceful-fs.js:143:5)
    at OpenReq.done (/root/app/node_modules/component-resolver/node_modules/graceful-fs/graceful-fs.js:63:22)
    at OpenReq.Req.done (/root/app/node_modules/component-builder/node_modules/graceful-fs/graceful-fs.js:143:5)
    at OpenReq.done (/root/app/node_modules/component-builder/node_modules/graceful-fs/graceful-fs.js:63:22)
    at Object.oncomplete (fs.js:108:15)
  democracyos:build Found error building styles: Error: failed to read "cristiandouce~loading-lock@0.1.0"'s file "loading-lock.css" +23ms
  democracyos:build Files copied successfully +9ms
^Cmake: *** [run] Interrupt

root@ip-10-183-228-36:~/app#

**Comment by jesseparker** [comment]
When I run "component build" and then "make" it works for me, and I don't get the runtime errors.

**Comment by gvilarino** [comment]
This is not a bug or a feature request; according to [our contribution guidelines](https://github.com/DemocracyOS/app/blob/development/CONTRIBUTING.md) this shouldn't be an issue.

Please go to our official gitter channel for help with this kind of things: [![Gitter](https://badges.gitter.im/Join%20Chat.svg)](https://gitter.im/DemocracyOS/app?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge)
