### ISSUE TITLE
Add segment.io

### ISSUE THREAD

**Issue by gvilarino** [DemocracyOS/app#791]
This replaces #782 and #783 

Track the following events:
- [x] Signin
- [x] Signup
- [x] Logout
- [x] Comment
- [x] Upvote comment
- [x] Downvote comment
- [x] Unvote comment
- [x] Vote
- [x] Navigation between pages

**Comment by jfresco** [comment]
Related: https://github.com/DemocracyOS/hub/issues/101

**Comment by gvilarino** [comment]
^yea

This also means adding proper funnels. This is of course due after 1.0 release.
