### ISSUE TITLE
Exclude index.js files from watched files

### ISSUE THREAD

**Issue by gvilarino** [DemocracyOS/app#798]

**Comment by jfresco** [comment]
To get the files bundled by Browserify, make a plugin based on this [Gist](https://gist.github.com/jfresco/973a9bc41a55c692d675).

**Comment by jfresco** [comment]
[This](https://github.com/gulpjs/gulp/blob/master/docs/recipes/fast-browserify-builds-with-watchify.md) is worth reading.

**Comment by gvilarino** [comment]
@jfresco what's the status on this?

**Comment by jfresco** [comment]
Not even started.
