### ISSUE TITLE
SaaS democracy URL handling

### ISSUE THREAD

**Issue by gvilarino** [DemocracyOS/app#799]
Multi-democracy (i.e.: hub-ish) deployment URLs should look like:

`domain.com/democracyname/topic/topicId`

whereas single-democracy (i.e.: like pre-1.0 deployments) URLs should look like:

`domain.com/topic/topicId`

The decision should be based on a configuration setting and both the client and the server should be able to distinguish between the approaches. This means it's not just a `page.js` problem.

**Comment by slifszyc** [comment]
Add max length strings validation on `forum` model
