### ISSUE TITLE
Sign up issues

### ISSUE THREAD

**Issue by tarasdudar** [DemocracyOS/app#802]
I've had this problem a couple of days ago and now other users are reporting it as well. While trying to validate the email users are getting the following error:

 "No token for id 554a69b0dfa7eb0300bdb810".

In my case I had to resend the validation email several times and tried different browsers before I finally was able to pass the validation stage. I've seen this problem before as well. I'm not sure what might be going on. I don't see anyone else reporting this problem. What could be a possible cause for this?

**Comment by jfresco** [comment]
@tarasdudar: The tokens are stored in the `token` collection on the database. You can query it by doing `db.tokens.find({ "_id": ObjectId("tokenid") })` on a MongoDB console connected to your database.
The token document is deleted once is validated. Please check again the workflow by querying the database.
Also check if the `userValidated` field for the user is set to `true`.

**Comment by gvilarino** [comment]
Another possible cause is that emails get delayed (for some mandrill issue) and you end up clicking a validation link *after* you re-sent a validation email. When that happens, the token generated during registration is invalidated and only the latest one (that hasn't yet arrived to your inbox) is valid.

**Comment by tarasdudar** [comment]
thanks @gvilarino,

this could have been a problem in my case although since I have seen this error before and was expecting the above behavior I was trying to make sure I wait long enough to get the latest validation email for each attempt. I thought that maybe it was related to the browser. I was initially using IE and then tried my phone and Chrome.

Here is the behavior described by one of the users. After the initial several failed attempts she is trying to register once a day and waits long enough for the validation email. She still gets the error. She is using Windows 8 with the latest version of IE.

So far I'm the only one who was able to register.

@jfresco,

I have not had any experience dealing with the databases. If you think this would be helpful could you please send me the set of commands to run and I'll post the results.

Thanks.

**Comment by gvilarino** [comment]
This may be related to #764

**Comment by mjlescano** [comment]
@tarasdudar did #764 fixed it? Could you try deploying the [last release](https://github.com/DemocracyOS/app/releases/tag/0.17.4)?
