### ISSUE TITLE
Dependencies pointing to GitHub

### ISSUE THREAD

**Issue by jfresco** [DemocracyOS/app#819]
There are deps on `package.json` that points to GitHub repositories like:
- [x] `"confirmation-component": "git://github.com/slifszyc/confirmation"`
- [x] `"ga": "git://github.com/jfresco/ga.git#add/package-json"`
- [x] `"list.js": "git://github.com/slifszyc/list.js"`
- [x] `"loading-lock": "git://github.com/jfresco/loading-lock.git#add/package-json"`
- [x] `"timeago": "git://github.com/jfresco/timeago.git#master"`
- [x] `"Snap.js": "git://github.com/jfresco/Snap.js.git#add/package-json"`
- [x] `"toggle-parent": "git://github.com/jfresco/toggle-parent.git#fix/npm-dependencies"`
- [x] `"headroom.js": "git://github.com/WickyNilliams/headroom.js.git#master"`
- [x] `"wrap": "git://github.com/jfresco/wrap#master"`
- [x] `"component-tip": "git://github.com/slifszyc/tip"`
- [x] `"side-comments": "git://github.com/DemocracyOS/side-comments#fix/npm-entry-point"`
- [x] `"datepicker": "git://github.com/slifszyc/datepicker"`
- [x] `"quill": "git://github.com/DemocracyOS/quill"`
- [x] `"toggle": "git://github.com/slifszyc/toggle"`
- [x] `"emitter": "git://github.com/mango/emitter"`

Deep dependencies:
- [x] `"calendar": "git://github.com/slifszyc/calendar#0.1.1"`
- [x] `"popover": "git://github.com/slifszyc/popover"`
- [x] `"bounds": "git://github.com/slifszyc/bounds"`
- [x] `"normalize": "git://github.com/slifszyc/normalize"`
- [x] `"aurora": "git://github.com/DemocracyOS/aurora"`
- [x] `"aurora-calendar": "git://github.com/DemocracyOS/aurora-calendar"`
- [x] `"aurora-tip": "git://github.com/DemocracyOS/aurora-tip"`
- [x] `"aurora-popover": "git://github.com/DemocracyOS/aurora-popover"`
- [x] `"@segmentio/extend": "git://github.com/segmentio/extend"`
- [x] `"javve-events": "git://github.com/slifszyc/javve-events"`
- [x] `"get-by-class": "git://github.com/slifszyc/get-by-class"`
- [x] `"get-attribute": "git://github.com/slifszyc/get-attribute"`
- [x] `"natural-sort": "git://github.com/slifszyc/natural-sort"`
- [x] `"to-string": "git://github.com/slifszyc/to-string"`
- [x] `"prevent": "git://github.com/slifszyc/prevent"`
- [x] `"stop": "git://github.com/slifszyc/stop"`

We should publish to npm registry what are our's and PR + contact the author to publish their's.

**Comment by slifszyc** [comment]
And migrate these repos to DemocracyOS organization, not on personal Github repositories

**Comment by slifszyc** [comment]
Done
