### ISSUE TITLE
User attributes on 'citizen/model' should be inside 'attributes' key

### ISSUE THREAD

**Issue by mjlescano** [DemocracyOS/app#830]
Instead of mixing the user attributes with the model properties and functions, also to avoid [this](https://github.com/DemocracyOS/app/blob/1.0.0/lib/citizen/model.js#L109) cleanup.

**Comment by gvilarino** [comment]
I don't agree. In any case, we should find a better approach for models/storage-objects. But an `attributes` key just kills the model API

**Comment by mjlescano** [comment]
Closing for now, this will be fixed at some point refactoring `1.0`.
