### ISSUE TITLE
Stylesheets organization and guidelines

### ISSUE THREAD

**Issue by jfresco** [DemocracyOS/app#832]
We need some kind of rules of organization about how we write and use the styles.
We had cases in where styles defined in `moduleA` collisions with those defined in `moduleB` _[a]_.
On the other hand, we need to have application-wide styles _[b]_ and styles applied where `moduleB` is used _[c]_.

Today we are wrapping the `template.jade` code in a `#moduleName` element, and using the same criteria in the `styles.styl` file, but I think this does not work with what we need in _b_.

Perhaps [Semantic CSS](http://www.smashingmagazine.com/2013/08/20/semantic-css-with-intelligent-selectors/) can rescue us, but we want to consider all alternatives and hear what the community have to say. The discussion is open.

**Comment by gvilarino** [comment]
I'd say the best thing would be starting out with a styleguide so can finally agree on styles for basic design elements and then addressing our custom styling with a structured, repeatable approach.

What about going bootstrap? Version 3 is looking great and could provide a way out until we get a full-time designer on board.

**Comment by slifszyc** [comment]
[The End of Global CSS](https://medium.com/seek-ui-engineering/the-end-of-global-css-90d2a4a06284) might help.

We can have some global styling for the structure of the site, buttons, links, etc. and have each component define some local styling

**Comment by mjlescano** [comment]
Just to have a starting point, I created a Wiki page with the first draft. Copied some rules from CONTRIBUTING.md and made it more `1.0.0` compatible:
https://github.com/DemocracyOS/app/wiki/Coding-Style-%5Bin-progress%5D

**Comment by slifszyc** [comment]
We will see what we'll do with the styles when we start using React.js

Inline styles?
CSS Modules?
