### ISSUE TITLE
URL inputs don't accept colons as a valid character

### ISSUE THREAD

**Issue by Farocs** [DemocracyOS/app#834]
Hello,

In my wiki, the URL have this form :
wiki.partipirate.org/Utilisateur:USER

But the contrôl block the ":" caracter.

Of course it's not a emergency ;)

**Comment by gvilarino** [comment]
Would you update `/lib/regexps/index.js` unde `url` so the RegExp accepts it and make a PR?

**Comment by jfresco** [comment]
Related: #840.
