### ISSUE TITLE
Implement HTTPOnly cookies

### ISSUE THREAD

**Issue by mjlescano** [DemocracyOS/app#846]
As mentioned by @jfresco at #836.

The disscussion here is that to do this we should change the logout functionality to make it do a request to the server, because right now we only unset the 'token' cookie to logout.

_**More info:** http://blog.codinghorror.com/protecting-your-cookies-httponly/_

**Comment by gvilarino** [comment]
:+1: to a request to the sever and marking the cookie. If something goes wrong with the request you can always note that the state is "logging out" and just re-call the logout endpoint later. Also, this would allow to navigate to a specific page after logout.
