### ISSUE TITLE
Problem loading module lib/config

### ISSUE THREAD

**Issue by VictorW1** [DemocracyOS/app#848]
Hello there, 

I'm new to using the Democracy OS system. I have gotten now to the point where my instance builds, I am "installed". I have two questions. When I navigate to http://localhost:3000/api, I get "Not Acceptable" , there doesn't seem to be anything there but it is running. I see in the guidelines that I need to set up data before I see anything. So as my first question: is there anything else I need to do before I see something on localhost:3000/api? What I'm trying to do is load tags and laws .json. The folllowing is my problem/actual question:

Ran in command line:
app$ node ./bin/dos-db load tag ./lib/fixtures/tags.json

Connecting to mongodb://localhost:27017/DemocracyOS-dev
Register mongoose models.

git/DemocracyOS/app/node_modules/mongoose/node_modules/mongodb/lib/mongodb/db.js:299
          throw err;
                ^
Error: Cannot find module 'lib/config'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/victor/git/DemocracyOS/app/lib/models/user.js:5:14)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)

Thanks,

Victor

**Comment by jfresco** [comment]
Hi @VictorW1.
For this kind of request, please use the [mailing list](https://groups.google.com/forum/#!forum/democracyos-app) or [Gitter](https://gitter.im/DemocracyOS/app?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge). We use GitHub Issues just for bugs and feature requests.

About your issue, please run the command again prepending `NODE_PATH=.`. The command should look like this:
```
app$ NODE_PATH=. node ./bin/dos-db load tag ./lib/fixtures/tags.json
```

For more information, take a look at [this wiki page](https://github.com/DemocracyOS/app/wiki/Load-fixtures).
