### ISSUE TITLE
Can't remove an argument

### ISSUE THREAD

**Issue by jfresco** [DemocracyOS/app#850]
When I try to remove an argument, the OK/Cancel buttons are not visible:

![image](https://cloud.githubusercontent.com/assets/4335188/7820603/de555c8e-03bf-11e5-9be6-95c286d916c4.png)

The error occurs in both `development` and `1.0.0` branches.

**Comment by gvilarino** [comment]
I've seen this working before. This must be something introduced by the 1.0 refactor

**Comment by jfresco** [comment]
@gvilarino Happens in `development` too.
