### ISSUE TITLE
Gravatar not shown in user badge

### ISSUE THREAD

**Issue by jfresco** [DemocracyOS/app#854]
![image](https://cloud.githubusercontent.com/assets/4335188/7822402/a48ab240-03cb-11e5-8ef9-ff71245a9392.png)

We have to do the same as in [`1.0.0`](https://github.com/DemocracyOS/app/commit/52b994a7a5cedb1a88d084ebda84d2e48e0823c5).

**Comment by gvilarino** [comment]
Maybe related to #855 ?

**Comment by jfresco** [comment]
No. Is not an issue related to using `https` protocol.
