### ISSUE TITLE
When you logout, the app should recalculate the locale based on the browser settings instead of the logging-out user's

### ISSUE THREAD

**Issue by mjlescano** [DemocracyOS/app#860]
As mentioned by @jfresco on #835

**Comment by gvilarino** [comment]
Let's put this on hold until somebody actually complains about it.

**Comment by slifszyc** [comment]
:+1: @gvilarino

**Comment by Istenais** [comment]
I can't even log out

**Comment by gvilarino** [comment]
@Istenais can you provide additional details?

**Comment by Istenais** [comment]
I get these lines when I try to log out 

democracyos:jwt Attempting to decode token... +48s
democracyos:jwt Token decoded successfully +18ms
democracyos:jwt Logging in user 555e3a40881b39b86badde2f +1ms

Basically when I click on "logout" website refreshes and it logins me back in.

**Comment by gvilarino** [comment]
Any additional info on what version of DemocracyOS you're using? That would help a lot. Try to run master and clear the database, and see if it happens again.

**Comment by Istenais** [comment]
DemocracyOS version is 0.17.3 
you can see live preview here http://tupodergt.com

**Comment by Istenais** [comment]
May these cause problems? http://pastebin.com/jnr15FeY

**Comment by jfresco** [comment]
@Istenais Seems to be other problem. You have one instance of the app running and you want to start another. Check if you have other terminal window or tab with an instance running. If you can't find it, restart your machine.

**Comment by Istenais** [comment]
@jfresco thanks, I got rid of these errors except bson module, but that doesnt solve logout issue.

**Comment by gvilarino** [comment]
The `BSON` error isn't breaking, it's just that because of the OS you use, there is no available native implementation of BSON serializing and it will fall back to a software implementation.

**Comment by jfresco** [comment]
@Istenais We are trying to solve the logout stuff. I think is already solved in the [`add/http-only`](https://github.com/DemocracyOS/app/tree/add/cookie-httponly) branch, but it is not officially released yet. Thanks for the patience :-)

**Comment by Istenais** [comment]
Great, thank you guys!
