### ISSUE TITLE
Don't show port number ':80' when making urls programmatically

### ISSUE THREAD

**Issue by mjlescano** [DemocracyOS/app#876]
**Convert:**
* `http://domain.com:80/callback` to `http://domain.com/callback`
* `https://domain.com:443/callback` to `https://domain.com/callback`

**Comment by AaronNGray** [comment]
https and port 80 ???
http and port 80
https and port 443 !

**Comment by mjlescano** [comment]
Clarified.

**Comment by gvilarino** [comment]
This won't work for `notifier` URLs. This is [a known issue](https://github.com/DemocracyOS/notifier-client/issues/8)

**Comment by fonorobert** [comment]
Notifier gets urls from signup-api which in turn uses `utils.buildUrl` to build the url, right? So we need to modify that function to check if the given port aligns with the default for the protocol and omit it if it does.

**Comment by gvilarino** [comment]
@fonorobert no, it's an issue with `notifier-client`. See the link I shared. PR's are welcome.

**Comment by fonorobert** [comment]
@gvilarino submitted
