### ISSUE TITLE
Rename PORT env variable. It does not work on Heroku

### ISSUE THREAD

**Issue by oscarguindzberg** [DemocracyOS/app#88]
Rename HOST and PORT env variables to something like APP_HOST, DEMOCRACYOS_HOST, same with port.
We are harcoding things now. Eg see proposal-article.js there is an "if" ignoring PORT unless we are in localhost
@cristiandouce says renaming the variable to something different than HOST makes code hard to understand. 
@oscarguindzberg says spreading "if"s makes the code even more difficult to understand. 
Let's hear what others have to say

**Comment by mjlescano** [comment]
@gvilarino @cristiandouce Right now we only have `publicPort` config and only use `env.PORT` [here](https://github.com/DemocracyOS/app/blob/development/index.js#L19) if it's defined. This issue could be closed?

**Comment by jfresco** [comment]
According to @mjlescano's comment, I'm closing this issue.
