### ISSUE TITLE
Fix styles on buttons and dropdowns

### ISSUE THREAD

**Issue by mjlescano** [DemocracyOS/app#889]
![captura de pantalla 2015-06-02 a las 17 45 02](https://cloud.githubusercontent.com/assets/558901/7946791/348ebd54-094f-11e5-99a9-2b24c00b5d3a.png)

Are not vertical aligned correctly.

**Comment by jfresco** [comment]
[This commit](https://github.com/DemocracyOS/app/commit/190ad633832edc400701d975035719c0f682e77c) seems to broke it:

![buttons](https://cloud.githubusercontent.com/assets/4335188/8530521/d58a0a48-23f7-11e5-9c4d-189614f4b27c.gif)

**Comment by mjlescano** [comment]
good call @jfresco, that padding was for the old font, sending fix.
