### ISSUE TITLE
Trying to do a "make run" on Ubuntu 14.04 Desktop

### ISSUE THREAD

**Issue by kishan-gauri** [DemocracyOS/app#906]
make[1]: Leaving directory `/home/kishan/node_modules/mongoose/node_modules/mongodb/node_modules/bson/build'

> DemocracyOS@0.17.4 postinstall /home/kishan
> node ./bin/dos-install --config && node ./bin/dos-build

       fatal : no remote found for dependency "marcuswestin/store.js".

npm ERR! weird error 1
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian
 
npm ERR! not ok code 0
make: *** [packages] Error 1

**Comment by fonorobert** [comment]
Try starting over (`make clean` or delete the repo and clone it again). Also make sure your Github username and password are set as env variables (see https://github.com/DemocracyOS/app/wiki/Installation#unix-and-osx)

**Comment by jfresco** [comment]
Thanks @fonorobert.
@kishan-gauri If you have further questions regarding to the installation process, please let us know in our [mailing list](https://groups.google.com/forum/#!forum/democracyos-app).
Closing.
