### ISSUE TITLE
[hub] - Add forum model on client side

### ISSUE THREAD

**Issue by slifszyc** [DemocracyOS/app#911]
It should be a singleton like `user` right now, and load whenever the user changes the forum he's on.

**Comment by mjlescano** [comment]
2 important files added:

`/lib/forum-model/model.js`: It's the client side model that is meant to be instantiated by any forum.
  * It has 2 methods that are important:
    + `.fetch()`: Returns a Promise, forcefully updates de model attributes with database data.
    + `.load()`: Returns a Promise, only makes a fetch() one time, unless `.unloaded()` is called

```javascript
import Forum from '../forum-model/model'

let forum = new Forum('debate-zone')

forum.load()
  .then(() => {
    console.log('Correctly loaded from database!')
  })
  .catch(() => {
    console.log('There was a connection error, server error, or doesnt exists.')
  })
``` 

`/lib/forum-model/user-forum.js`: Extends `model.js` but always fetches the current loggedin user forum, and implements `.exists()` that returns a `Boolean` telling if the user has a forum.

```javascript
import userForum from '../forum-model/user-forum'

if (userForum.exists()) console.log('User has a forum!')
```
