### ISSUE TITLE
Normalize layout presentation from a single point

### ISSUE THREAD

**Issue by mjlescano** [DemocracyOS/app#912]
We should have, on `lib/layout/layout.js` a single file that takes care of the elements that are currently loaded on the Layout.

Instead of doing something like this on every page load:
```javascript
  o('body').addClass('forum-new');
  var section = o('section.site-content').empty();
  var view = new View();
  view.appendTo(section[0]);
```

We should do something like:
```javascript
import layout from `../lib/layout/layout`
import Sidebar from `../lib/sidebar/sidebar`
import View from `./view`

let sidebarView = new Sidebar({ template: sarasa })
let feedView = new View({ template: sarasa})

// Render the page.
layout.load({
  className: 'feed-page'
  sidebar: sidebarView, // If given `true` it will leave the currently instantiated sidebar (?)
  content: feedView // Will take care un removing the current content and put `feedView` instead
})
```

And the method `load` (or wathever) will take care of un-instantiating the current views (if exists) and removing the las `className` in favor of the new one (and emitting events maybe).

**Comment by slifszyc** [comment]
Let's wait until we start using React.js to see how we can rewrite this logic, instead of rewriting it twice
