### ISSUE TITLE
Stop using 'lib/emitter' and use an external library

### ISSUE THREAD

**Issue by mjlescano** [DemocracyOS/app#913]
it's implemented with the same interface here: https://github.com/medikoo/event-emitter

**Comment by mjlescano** [comment]
Also, it would be nice to use [Backbone Events](https://github.com/n1k0/backbone-events-standalone) because it has `.listenTo(Object, event, callback)` and `stopListeningTo(Object, [event])` methods, that allow to stop listening to a specific object in a much simpler way.

**Comment by jfresco** [comment]
+1
I'm ashamed of that. The problem is that we can't `import` clases written in ES6 (Babel bug? Browserify bug? -- We have to do a little research here). So, in order to mantain the `class Foo extends Emitter` syntax, I had to get the module and import it locally.

I have doubts with the Backbone Events stuff. I think this implies to rewrite all the `View`s and I can't see what's the trade here. Are we having a serious problem here?

**Comment by jfresco** [comment]
Neither Backbone Events nor AmpersandJS Events have a smooth way to be used with ES6 classes.

**Comment by mjlescano** [comment]
Not really, `listenTo()` It's mostly a hip _dev-love_ stuff. It's more semantic, and useful when you want to stop listening several objects all at once.

Without `listenTo`:
```javascript
B.on('sarasa', cb, A)
B.on('pepepe', cb, A)
C.on('sarasa', cb, A)

B.off(null, null, A)
C.off(null, null, A)
```

With `listenTo`:
```javascript
A.listenTo(B, 'sarasa', cb)
A.listenTo(B, 'pepepe', cb)
A.listenTo(C, 'sarasa', cb)

A.stopListening()
```

_**Edit:** Changed my recomendation from Backbone Events to AmpersandJS's_

**Comment by jfresco** [comment]
Still not seeing the trade. We are bundling a whole new library just to make code a little bit more readable, having to rewrite the 100% of the `View`s.
I think I'm missing something.

How would you rewrite the `CommentsFilter` class using AmpersandJS Events?

```js
export default class CommentsFilter extends View {
  constructor () {
    super();
    this.refresh();
    super(template, { label: this.get().label, sorts: sorts });
  }

  /**
   * Switch on events
   *
   * @api public
   */

  switchOn () {
    bus.on('page:change', this.bound('switchOff'));
    this.bind('click', 'li a', 'onsortclick');
    this.on('change', this.bound('onsortchange'));
    user.on('load', this.bound('refresh'));
    let dropdownBtn = this.find('.btn');
    this.dropdown = new ToggleParent(dropdownBtn[0]);
  }


  switchOff () {
    bus.off('page:change', this.bound('switchOff'));
    user.off('loaded', this.bound('refresh'));
    if (this.dropdown) {
      this.dropdown.destroy();
      this.dropdown = null;
    }
  }
```

**Comment by mjlescano** [comment]
Bummer about babel, let's discuss it more later.

Yup, It's not that much gain. It would be:
```javascript
  switchOn () {
    this.bind('click', 'li a', 'onsortclick');

    this.listenTo(bus, 'page:change', this.bound('switchOff'))
    this.listenTo(user, 'load', this.bound('refresh'))
    this.on('change', this.bound('onsortchange'))

    let dropdownBtn = this.find('.btn');
    this.dropdown = new ToggleParent(dropdownBtn[0]);
  }


  switchOff () {
    this.stopListening()
    if (this.dropdown) {
      this.dropdown.destroy();
      this.dropdown = null;
    }
  }
```

The really nice thing is that for every event we add on `switchOn`, we don't have to add it on `switchOff`. Avoids repetition.

**Comment by mjlescano** [comment]
It's not a solution, but at least we don't have to maintain `Emitter`:

```javascript
import EventsPrototype from 'ampersand-events'

var Events = function(){}
Events.prototype = EventsPrototype

export default class Mirtha extends Events {
  insult () {
    this.trigger('insult')
  }
}
```

Here's how I tested it: https://github.com/mjlescano/test-es6-class-extension

Should also work with https://github.com/component/emitter this way (not tested):
```javascript
import ComponentEmitter from 'component-emitter'

function Emitter(){}
ComponentEmmiter(Emitter)

export default class Mirtha extends Emitter {
  // ...
}
```

**Comment by mjlescano** [comment]
[Mango/emitter](https://github.com/mango/emitter) worked with babel!

1. Install it
`npm i Mango/emitter --save`

2. Extend it
  ```javascript
    import Emitter from 'emitter'
    export default class Piringulete extends Emitter {
      ...
    }
  ```

3. Profit it (?)
  ```javascript
    let pirin = new Piringuelete;
    pirin.on('fired', function() { console.log('Wow. Such event. So profit.') })
    pirin.emit('fired') // Wow. Such event. So profit.
  ```
