### ISSUE TITLE
Open voting

### ISSUE THREAD

**Issue by tarasdudar** [DemocracyOS/app#926]
Is there a way to make the voting process completely open? Display the current count of all the votes and somehow provide the access to the database where everyone could see how everyone has voted. This would be similar to the open voting in the parliament where every representative has to publicly state their vote one by one. I think this would help to build trust and credibility with the users.

**Comment by fonorobert** [comment]
Displaying the current count to everyone is pretty simple: remove the `if` from ln 51 in `proposal-options/template.jade` (https://github.com/DemocracyOS/app/blob/development/lib/proposal-options/template.jade#L51).

**Comment by gvilarino** [comment]
Just as @fonorobert says, that's as much as we can provide right now. We do have plans for providing complete results per user, but we're not there yet.

**Comment by fonorobert** [comment]
@gvilarino when to display results could be a config key. This way it would be easy to setup if you want the results to show always or just after voting is closed. What do you think?

**Comment by gvilarino** [comment]
Yeah, it could be easily done. Care to PR?

**Comment by fonorobert** [comment]
@gvilarino  I'm trying to put the PR together and when I add `var config = require("config")` to proposal-options.js the app hangs after logging `democracyos:law Serving laws`.
I checked how other views used config and there didn't seem to be any trick to it. What am I doing wrong?

**Comment by mjlescano** [comment]
@fonorobert should be `var config = require('lib/config')`

**Comment by fonorobert** [comment]
@mjlescano same result for `lib/config` and `../config`

**Comment by mjlescano** [comment]
Weird, It worked for me this way: https://github.com/DemocracyOS/app/tree/test-proposal-options-config maybe is something else? If you want push the branch you're working and I'll revise it.

Also, noticed [this](https://github.com/DemocracyOS/app/commit/13f2d07b8852ede7be324b77f85e4f80921ee876) bug, maybe has to do something with the error.

**Comment by fonorobert** [comment]
this should work in theory, but it still hangs for me
