### ISSUE TITLE
questions: isn't it annoying to touch so many files if upgrading a remote dependency?

### ISSUE THREAD

**Issue by timaschew** [DemocracyOS/app#927]
for instance: if you want to upgrade __component/dom__ you need to touch 24 files:

https://github.com/DemocracyOS/app/search?p=2&q=component%2Fdom&utf8=%E2%9C%93

**Comment by gvilarino** [comment]
Yeah, that's one of the problem's we've faced with `component`, as well as hitting the github API rate-limit way too often.

We've been exploring with browserfify as a solution for the frontend build recently and we're probably adopting it as a definite solution for this. We love the `component` approach to modularization, but the absence of a registry and depending entirely on the github API dosn't scale for mid-to-large project like ours :/

**Comment by timaschew** [comment]
> as well as hitting the github API rate-limit way too often.

even if you use a token?

> but the absence of a registry and depending entirely on the github API dosn't scale for mid-to-large project like ours :/

yes, totally agree. There are also some other drawbacks.

Currently I'm experimenting with jspm. It is really awesome, it's like component also a package manager and support github and npm.
Just now I setup a configuration in jspm to support component styled directory structures and require paths, so it's working without touching the code!
I will write a blog article and maybe a small tool to convert component apps into jspm.

R.I.P component

**Comment by gvilarino** [comment]
> even if you use a token?

Yeah, even with a token, 2 out of 3 (clean) builds would fail. For new instances, we would usually have to push 2-4 times to heroku to get a working deployment.

We'll definitely check `jspm` out. Is there any repo/gist you'd recommend us checking out?

> I will write a blog article and maybe a small tool to convert component apps into jspm.

Looking forward to it!

> R.I.P component
:(

**Comment by timaschew** [comment]
https://github.com/jspm/demo-es6
https://github.com/guybedford/jspm-demo
Am 14.06.2015 17:00 schrieb "Guido Vilariño" <notifications@github.com>:

**Comment by gvilarino** [comment]
Thanks!

**Comment by timaschew** [comment]
turns out webpack has a better and more configurable API.

see https://github.com/componentjs/component/issues/639

**Comment by gvilarino** [comment]
:+1:
