### ISSUE TITLE
Version endpoint should force accept JSON header

### ISSUE THREAD

**Issue by gvilarino** [DemocracyOS/app#940]
Currently, if you navigate or `curl` to `democracyos.domain.com/api` you'll get a `406` or `Not acceptable` response.

I think API endpoints should always force the `Accept` header to `application/json` if not already specified. Or something like that.

Related to #444

**Comment by mjlescano** [comment]
I don't think there's a need to force the client to set `Accept: application/json` on request Header in this case.

That only would be useful if `/api` could respond with different formats, so, the client should set `Accept: application/json` or `Accept: application/html` or wathever. But this is not the case, it always responds with `Content-type: application/json`.
