### ISSUE TITLE
Use a translation library that allows lexical differences between languages

### ISSUE THREAD

**Issue by tarasdudar** [DemocracyOS/app#949]
I've found another instance where "s" is added to the variable to make it plural. This is similar to what we used to have with "Participant" vs "Participants".

In this case the variable name is "proposal-options.vote-item".

Just a reminder for future references. Even though adding "s" to the end of the word works fine for English language it does not work for other languages. For example in Russian and Ukrainian there are three different words used for the following count cases:

1
2-4
5 and more

Also the letter "s" is not a part of Cyrillic alphabet and probably many other alphabets.

Ideally 3 different variables would work the best for Russian and Ukrainian translations every time there needs to be distinction between single and plural, but even 2 would work OK as I hope we will always have more than 5 participants and votes.

**Comment by tarasdudar** [comment]
Actually there is one correction to the above description. Here is how three different words are used in Russian and Ukrainian.

1 and every other number that ends with 1 (*1) except 11

2, 3, 4 and every other number that ends with 2, 3 or 4 (*2, *3, *4) except 12, 13 and 14

0, 5, 6, 7, 8, 9, 11, 12, 13, 14 and every other number that ends with 0, 5, 6, 7, 8 or 9 (*0, *5, *6, *7, *8, *9)

Taking this into consideration 3 variables would probably work the best.

**Comment by fonorobert** [comment]
I agree, in these instances there should be a separate pluralised key for the phrase instead of the hard-coded 's'.

**Comment by mjlescano** [comment]
A solution would be to start using [i18next](http://i18next.com/index.html):
* Works with `.json` translation files (will need to convert our dots namespace to objects when loading the files with [dot-object](https://www.npmjs.com/package/dot-object))
* Works with express: http://i18next.com/node/index.html
* Works with browserify: https://www.npmjs.com/package/i18next-client
* Has pluralization resolved: http://i18next.com/node/pages/doc_features.html#plurals

**Comment by jfresco** [comment]
Like that :point_up_2:

**Comment by gvilarino** [comment]
I guess we can make this an issue for post `1.0`

**Comment by slifszyc** [comment]
http://formatjs.io/ <-- the posta

**Comment by slifszyc** [comment]
Let's continue this on https://github.com/DemocracyOS/app/issues/1035
