### ISSUE TITLE
Page blank

### ISSUE THREAD

**Issue by johnfelipe** [DemocracyOS/app#953]
This is my process:

**sudo npm install**
and

**sudo NODE_ENV=production make**

	felipe@Democraciaenlinea:~/app$ sudo NODE_ENV=production make
	Installing dependencies...
	npm WARN package.json co-prompt@1.0.0 No repository field.
	npm WARN package.json t-component@1.0.0 repo should probably be repository.
	npm WARN package.json type-component@0.0.1 No repository field.
	npm WARN cannot run in wd DemocracyOS@0.17.6 node ./bin/dos-install --config && node ./bin/dos-build (wd=/home/felipe/app)
	Starting application...
	  democracyos:translations Warning: Missing translation keys on 'ca': +0ms
	  democracyos:translations   - settings.locale.hu +1ms
	  democracyos:translations   - signin.login-with-facebook +1ms
	  democracyos:translations Warning: Missing translation keys on 'de': +0ms
	  democracyos:translations   - settings.locale.hu +0ms
	  democracyos:translations   - signin.login-with-facebook +0ms
	  democracyos:translations Warning: Missing translation keys on 'fi': +0ms
	  democracyos:translations   - settings.locale.hu +1ms
	  democracyos:translations   - signin.login-with-facebook +0ms
	  democracyos:translations Warning: Missing translation keys on 'fr': +0ms
	  democracyos:translations   - settings.locale.hu +0ms
	  democracyos:translations   - signin.login-with-facebook +0ms
	  democracyos:translations Warning: Missing translation keys on 'gl': +0ms
	  democracyos:translations   - settings.locale.hu +0ms
	  democracyos:translations   - signin.login-with-facebook +0ms
	  democracyos:translations Warning: Missing translation keys on 'it': +0ms
	  democracyos:translations   - settings.locale.hu +0ms
	  democracyos:translations   - signin.login-with-facebook +0ms
	  democracyos:translations Warning: Missing translation keys on 'nl': +0ms
	  democracyos:translations   - settings.locale.hu +1ms
	  democracyos:translations   - signin.login-with-facebook +0ms
	  democracyos:translations Warning: Missing translation keys on 'pt': +0ms
	  democracyos:translations   - settings.locale.hu +0ms
	  democracyos:translations   - signin.login-with-facebook +0ms
	  democracyos:translations Warning: Missing translation keys on 'ru': +0ms
	  democracyos:translations   - settings.locale.hu +0ms
	  democracyos:translations   - signin.login-with-facebook +0ms
	  democracyos:translations Warning: Missing translation keys on 'sv': +0ms
	  democracyos:translations   - settings.locale.hu +0ms
	  democracyos:translations   - signin.login-with-facebook +0ms
	  democracyos:translations Warning: Missing translation keys on 'uk': +0ms
	  democracyos:translations   - settings.locale.hu +0ms
	  democracyos:translations   - signin.login-with-facebook +0ms
	  democracyos:db Using mongodb hosts: localhost:27017 +309ms
	  democracyos:db Using mongodb URI: mongodb://localhost:27017/DemocracyOS-dev +0ms
	  democracyos:db Connecting to MongoDB database DemocracyOS-dev +1ms
	  democracyos:root Server started at port 80. +1s
	  democracyos:db Connected to MongoDB on URI: mongodb://localhost:27017/DemocracyOS-dev +30ms
	  democracyos:db Connection to MongoDB is now OPEN on URI: mongodb://localhost:27017/DemocracyOS-dev +16ms
	  democracyos:jwt HTTP header x-access-token has no token. Moving on... +9s
	  democracyos:l10n Inferring user locale from HTTP header accept-language: es-ES,es;q=0.8,en;q=0.6 +1ms
	  democracyos:l10n Setting locale: es +0ms
	  democracyos:jwt HTTP header x-access-token has no token. Moving on... +205ms
	  democracyos:l10n Inferring user locale from HTTP header accept-language: es-ES,es;q=0.8,en;q=0.6 +1ms
	  democracyos:l10n Setting locale: es +0ms
	  democracyos:jwt HTTP header x-access-token has no token. Moving on... +91ms
	  democracyos:l10n Inferring user locale from HTTP header accept-language: es-ES,es;q=0.8,en;q=0.6 +0ms
	  democracyos:l10n Setting locale: es +1ms

But page blank
How fix that

**Comment by johnfelipe** [comment]
Then how fix it?

**Comment by gvilarino** [comment]
@johnfelipe we don't provide support for specific user problems via our github issues. Please refer to [our gitter channel](gitter.im/DemocracyOS/app) for help
