### ISSUE TITLE
instal en hot web ?

### ISSUE THREAD

**Issue by bobkerman** [DemocracyOS/app#954]
hola, quisiera saber si alguien me podria decir si puedo instalar democracyos en un hotweb, y si se puede agradeceria si alguien me puede pasar una guia sobre como hacerlo, estoy demaciado perdido

Hello, I wonder if someone could tell me if I install a Hotweb democracyos, and if you can appreciate if someone can spend a guide on how to do, I'm way too lost

**Comment by gvilarino** [comment]
Please address questions like this to our gitter or our official mail group; as stated in our [contribution guidelines](https://github.com/DemocracyOS/app/blob/development/CONTRIBUTING.md) we don't answer user-specific inquiries in our issues.
