### ISSUE TITLE
Change language option list from display language to actual language

### ISSUE THREAD

**Issue by fabriciodisalvo** [DemocracyOS/app#963]
When using the app in English, for example, the language option list is shown in English:

![image](https://cloud.githubusercontent.com/assets/13111082/8466628/2baa5eee-202b-11e5-8c9a-1ab4baf0c3ee.png)

Proposing update those lists to 
> Original Language / Display Language

as follows:

>Català / Catalan
>Deutsche / German
>English / English
>Español / Spanish
>Suomi / Finnish
>Français / French
>Galego / Galician
>Magyar / Hungarian
>Italiano / Italian
>Nederlands / Dutch
>Português / Portuguese
>Русский / Russian
>Svenska / Swedish
>Українська / Ukrainian

**Comment by mjlescano** [comment]
+1
