### ISSUE TITLE
Create democracyos.github.io

### ISSUE THREAD

**Issue by slifszyc** [DemocracyOS/app#984]
The idea is to have a special site dedicated for the developers about the app.

It must include:
- [ ] information about installation, configuration and running processes
- [ ] some description about the technology we are using (node.js, browserify, Babel, jade, etc)
- [ ] screenshots of the main features
- [ ] tutorials on how to use the admin, how to add translation keys, how to deploy to heroku, how to release a new version and other "How to's"...
- [ ] contributing to DemocracyOS
- [ ] use cases and experiences all around the world 
- [ ] links to DemocracyOS gitter and mailing list

**Comment by gvilarino** [comment]
I would argue that we shold aim for either `democracyos.org` or `democracyos.io` for this website

**Comment by slifszyc** [comment]
Related: https://github.com/DemocracyOS/app/issues/454

**Comment by mjlescano** [comment]
http://docs.democracyos.org/ :smiley:
