### ISSUE TITLE
interoperability with the official law repositories... URN LEX?

### ISSUE THREAD

**Issue by ppKrauss** [DemocracyOS/app#988]
There are no [*de facto* international standard](https://en.wikipedia.org/wiki/De_facto_standard) for law-project identification, like [DOI](https://en.wikipedia.org/wiki/Digital_object_identifier) for [research paper](https://en.wikipedia.org/wiki/Scientific_literature) identification.  

Brasil was demonstrated that the  [LEX URN](https://en.wikipedia.org/wiki/Lex_(URN)) is a possible choice: http://www.lexml.gov.br/

... But the suggestion is only "Lets adopt a standard for identify documents", because it is the basic starting point for systems interoperability.

**Comment by gvilarino** [comment]
We've discussed this quite a bit of times with the team and the broad organisation. We have plans for adding an API that exposes `topics` in a machine-readable fashion. However, we do believe that an `XML`-based standard is the wrong way to go; we would only pursue `JSON`-based solutions for this matter.

As a personal opinion, `XML` should dissapear :bomb:

**Comment by ppKrauss** [comment]
ops, please, pay attention, check the links, my text is not about XML (!)  ;-)

Lets restart from zero...  Any Federal Law in Brazil have a page with a catalographic informations of the law at LexML portal.  Example: *Federal Law number 12965 of year 2014*, it have an [official PURL](https://en.wikipedia.org/wiki/Persistent_uniform_resource_locator) at 
  http://www.lexml.gov.br/urn/urn:lex:br:federal:lei:2014;12965

In this  (persistent) URL , the prefix `http://www.lexml.gov.br/urn/`  is a URN resolver, and the suffix `urn:lex:br:federal:lei:2014;12965` is an extact translating to "Federal Law number 12965 of year 2014":

* Brazilian's legislative documents: `urn:lex:br` (Argentina is `urn:lex:ar`)
* "Federal" authority: `:federal`
* Law-type: `:lei`
* Year: `2014`
* Authority's ID: `12965`

so, URN LEX is an URN schema to *transparent unique identification* of law-documents. 

PS1: "transparent ID" here is the fact that it depends only of metadata, not depends on central ID-controll as usual opaque ID in databases or hash generators.


PS2: of course, the URN-Resolver can use JSON to communicate as a REST webservice ;-)

**Comment by slifszyc** [comment]
This looks interesting, having a global id for laws, like a ISBN for books.

Thing is on DemocracyOS we work with `topics`, as Guido said, and not only with `laws`.

This could be made possible on a fork and shouldn't be more difficult than adding an attribute on the `TopicSchema`
