### ISSUE TITLE
Curatorial management

### ISSUE THREAD

**Issue by ppKrauss** [DemocracyOS/app#990]
(this issue is perhaps a *new feature request*)

The usual in DemocracyOS implementations (sites), is to encourage councilors to expose their [law-projects](http://wiki.partidodelared.org/index.php/Despacho), as in [EuVoto-fork site](http://euvoto.org/) *modus operandi*, so the projects are selected by legislators and a little body of trustees... But other *modus operandi* is possible: public (users) selecting the law-projects to be submited at the voting.

The simplified  process is:

1. User selects a law-project (from an "[universe of thousands of law-projects](http://www.lexml.gov.br/busca/search?keyword=&f1-tipoDocumento=Proposi%C3%A7%C3%B5es%C2%A0Legislativas)"), and  submits it to appreciation; 

2. All users vote (like or dislike) the submitted law-project, creating an *"accepted projects queue"* (perhaps ordered by consensus/relevance degree);

3.  A task-force prepare the project's presentation (synopsis and youtube) of each law-project in the queue.
 
So, this is what a "open curatorial management" do... There are an DemocracyOS iniciative (working group) or fork with this features? 

## Notes

A "wide public" is not feasible, in general  only a subset of this "public" will be responsible by its actions. They need a login, and perhaps some previous responsibility-agreement about what will be published in the site... So, we can say that this "subset of the public" is the *curatorial body* of the DemocracyOS site.

**Comment by slifszyc** [comment]
This could be a fork of DemocracyOS but is not currently on the project's roadmap
