### ISSUE TITLE
dos-install should retry when component install fails

### ISSUE THREAD

**Issue by ddouglascarr** [DemocracyOS/app#991]
The bin/dos-install script can fail when fetching componentJS components. 

I've experienced this, and it has been talked about here:
https://gitter.im/DemocracyOS/app/archives/2015/05/01

Not a huge deal, as you can just re-run until it works. However, I'm working on a vagrant setup, so this sort of thing really can't happen. 

Pull request coming.

**Comment by gvilarino** [comment]
@ddouglascarr thanks! Still, we're dropping `component` as of `1.0.0`. This is to be released this week so I'm not sure if it makes sense to add a fix for this.

**Comment by ddouglascarr** [comment]
You're releasing 1.0.0 this week? Congratulations and good luck!
