### ISSUE TITLE
Add ES6 generators on front-end

### ISSUE THREAD

**Issue by mjlescano** [DemocracyOS/app#993]
This would allow us, for example if we want to find a topic and then its forum:

Instead of this:
```javascipt
return topicStore.findOne('1283128973')
  .then(topic => {
    forumStore.findOne(topic.forum)
    return forum
  })
```

Do this:
```javascipt
return co.wrap(function *(){
  let topic = yield topicStore.findOne('1283128973')
  let forum = yield forumStore.findOne(topic.forum)
  return forum
})
```

#### To Install
As pointed out in [this issue](https://github.com/babel/babelify/issues/28), first we have to add the [Regenerator Polyfill](http://facebook.github.io/regenerator/) to Babel. And then, for generators niceities, add [tj/co](https://github.com/tj/co)

**Comment by gvilarino** [comment]
I agree the second example looks nicer, but if we need to add 2 dependencies (especially a polyfill) to our codebase just for that I don't know if it's worth it.

**Comment by slifszyc** [comment]
:point_up: only if it's worth it

**Comment by slifszyc** [comment]
http://pouchdb.com/2015/03/05/taming-the-async-beast-with-es7.html better

**Comment by mjlescano** [comment]
:heart_eyes:
